Repository AIcrowd/AIcrowd, pull requests merged in 2020-06, with the labels that each got.

#1510 Show error messages in Edit profile page
  app/controllers/participants_controller.rb
  app/views/participants/edit.html.erb
Labels: Review / Feedback Needed

#1518 Fix team invitation e-mails
  app/mailers/participants/invitations_mailer.rb
  app/views/participants/invitations_mailer/invitation_accepted_email.html.erb
  app/views/participants/invitations_mailer/invitation_canceled_email.html.erb
  app/views/participants/invitations_mailer/invitation_pending_email.html.erb
  config/sidekiq.yml
Labels: bug

#1520 Emails fixes
  app/controllers/participant_clef_tasks_controller.rb
  app/helpers/invitations_helper.rb
  app/jobs/organizers/eua_notification_job.rb
  app/views/admin/notifications_mailer/newsletter_email_notification_email.html.erb
  app/views/newsletter_emails_mailer/_unsubscribe_note.html.erb
  app/views/newsletter_emails_mailer/declined_email.html.erb
  app/views/participants/invitations_mailer/invitation_pending_email.html.erb
Labels: Review / Feedback Needed, bug

#1513 Fix dataset_files#show missing template error
  app/controllers/dataset_files_controller.rb
  config/routes.rb
Labels: Review / Feedback Needed, bug

#1515 Allow to use challenge dataset files in CLEF challenge
  app/controllers/clef_tasks_controller.rb
  app/controllers/concerns/dataset_files.rb
  app/controllers/dataset_files_controller.rb
  app/controllers/task_dataset_files_controller.rb
  app/helpers/participant_clef_tasks_helper.rb
  app/views/clef_tasks/_form.html.erb
  app/views/dataset_files/_dataset_files.html.erb
  app/views/dataset_files/index.html.erb
  app/views/task_dataset_files/index.html.erb
  app/views/task_dataset_files/resources/_participant_submitted.html.erb
  app/views/task_dataset_files/resources/_participant_unregistered.html.erb
  db/migrate/20200603151708_add_use_challenge_dataset_files_to_clef_tasks.rb
  db/schema.rb
Labels: Review / Feedback Needed

#1463 Add top three winners in leaderboards
  app/assets/images/img/award-bronze.svg
  app/assets/images/img/award-gold.svg
  app/assets/images/img/award-silver.svg
  app/assets/stylesheets/application-redesign.css.scss
  app/helpers/leaderboard_helper.rb
  app/models/participant.rb
  app/models/submission.rb
  app/models/team.rb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/leaderboards/_participant_submission_graph.html.erb
  app/views/leaderboards/_winners.html.erb
  app/views/leaderboards/index.html.erb
Labels: Review / Feedback Needed

#1521 Fix recent Rollbar errors
  app/assets/stylesheets/application-redesign.css.scss
  app/helpers/participants_helper.rb
  app/jobs/discourse/update_permissions_job.rb
Labels: Review / Feedback Needed, bug

#1526 Change css of code block
  app/assets/javascripts/ckeditor/plugins/codesnippet/lib/highlight/styles/sunburst.css
Labels: Review / Feedback Needed

#1527 Fix OldParticipant bug
  app/views/leaderboards/_leaderboards.html.erb
  app/views/leaderboards/_winners.html.erb
Labels: Review / Feedback Needed, bug

#1539 Add See all pending newsletters link to newsletter_email notification
  app/views/admin/notifications_mailer/newsletter_email_notification_email.html.erb
Labels: Review / Feedback Needed

#1237 Add leaderboard filters
  app/assets/images/img/icon-filter.svg
  app/assets/javascripts/controllers/leaderboards_controller.js
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/leaderboards_controller.rb
  app/helpers/leaderboard_helper.rb
  app/javascript/stimulus_js/controllers/leaderboards_controller.js
  app/lib/country.rb
  app/models/leaderboard/base_leaderboard.rb
  app/models/leaderboard/disentaglement_leaderboard.rb
  app/models/leaderboard/leaderboard.rb
  app/models/leaderboard/ongoing_leaderboard.rb
  app/policies/leaderboard_policy.rb
  app/policies/ongoing_leaderboard_policy.rb
  app/services/leaderboards/filter_service.rb
  app/views/leaderboards/_filter_leaderboards.html.erb
  app/views/leaderboards/get_affiliation.js.erb
  app/views/leaderboards/index.html.erb
  config/routes.rb
  spec/lib/country_spec.rb
  spec/policies/leaderboard_policy_spec.rb
  spec/policies/ongoing_leaderboard_policy_spec.rb
  spec/services/leaderboards/filter_service.rb
Labels: Review / Feedback Needed

#1315 Fix leaderboard social share
  app/assets/javascripts/controllers/leaderboards_controller.js
  app/assets/stylesheets/application-redesign.css.scss
  app/helpers/application_helper.rb
  app/helpers/meta_tags_helper.rb
  app/helpers/submissions_helper.rb
  app/views/layouts/application.html.erb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/submissions/_submissions.html.erb
  app/views/submissions/index.html.erb
  app/views/submissions/show.html.erb
Labels: Review / Feedback Needed

#1551 Remove imageClef from eua notification email
  app/mailers/organizers/notifications_mailer.rb
  spec/mailers/organizers/notifications_mailer_spec.rb
Labels: Review / Feedback Needed

#1543 Refactor submission trend codebase
  app/controllers/leaderboards_controller.rb
  app/helpers/leaderboard_helper.rb
  app/views/leaderboards/_participant_submission_graph.html.erb
Labels: Review / Feedback Needed

#1553 Display only visible topics and add paging to Discussion page
  app/controllers/challenges/discussions_controller.rb
  app/services/discourse/fetch_challenge_topics_service.rb
  app/views/challenges/discussions/_discussion_list.html.erb
  app/views/challenges/discussions/show.html.erb
  app/views/challenges/discussions/show.js.erb
  spec/services/discourse/fetch_challenge_topics_service_spec.rb
  spec/vcr/discourse_api/challenge_topics/success.yml
Labels: Review / Feedback Needed

#1550 Use paranoid mode in Devise and fix error messages
  Gemfile
  Gemfile.lock
  app/views/devise/registrations/new.html.erb
  app/views/layouts/application.html.erb
  config/initializers/devise.rb
Labels: Review / Feedback Needed

#1312 Refactor CalculateLeaderboardService
  app/jobs/calculate_leaderboard_job.rb
  app/models/challenge.rb
  app/models/leaderboard/base_leaderboard.rb
  app/models/leaderboard/previous_leaderboard.rb
  app/models/leaderboard/previous_ongoing_leaderboard.rb
  app/models/migration_mapping.rb
  app/models/submission.rb
  app/services/calculate_leaderboard_service.rb
  app/services/challenge_rounds/create_leaderboards_service.rb
  db/migrate/20200502080041_update_previous_leaderboards_to_version_5.rb
  db/migrate/20200502080127_update_previous_ongoing_leaderboards_to_version_4.rb
  db/migrate/20200609091902_remove_previous_leaderboards_and_previous_ongoing_leaderboards.rb
  db/schema.rb
  db/seeds.rb
  db/views/previous_leaderboards_v01.sql
  db/views/previous_leaderboards_v02.sql
  db/views/previous_leaderboards_v03.sql
  db/views/previous_leaderboards_v04.sql
  db/views/previous_leaderboards_v05.sql
  db/views/previous_ongoing_leaderboards_v01.sql
  db/views/previous_ongoing_leaderboards_v02.sql
  db/views/previous_ongoing_leaderboards_v03.sql
  db/views/previous_ongoing_leaderboards_v04.sql
  doc/leaderboard.md
  spec/factories/migration_mapping_factory.rb
  spec/factories/submission_factory.rb
  spec/features/leaderboard/leaderboard_invisible_completed_challenge_spec.rb
  spec/models/views/previous_leaderboard_spec.rb
  spec/services/calculate_leaderboard_ordering_spec.rb
  spec/services/calculate_leaderboard_same_rank_spec.rb
  spec/services/calculate_leaderboard_service_baseline_single_round_spec.rb
  spec/services/calculate_leaderboard_service_single_round_running_spec.rb
  spec/services/calculate_leaderboard_service_with_teams_spec.rb
  spec/services/challenge_rounds/create_leaderboards_service_spec.rb
  spec/services/vizdoom_leaderboard_spec.rb
Labels: Review / Feedback Needed

#1504 Feature/notification
  app/assets/images/img/discourse.png
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/api/v1/participants_controller.rb
  app/controllers/application_controller.rb
  app/controllers/participants_controller.rb
  app/helpers/application_helper.rb
  app/jobs/calculate_leaderboard_job.rb
  app/jobs/notification/leaderboard_notification_job.rb
  app/jobs/notification/submission_notification_job.rb
  app/models/notification.rb
  app/models/participant.rb
  app/models/submission.rb
  app/services/discourse/notification_service.rb
  app/services/notification_service.rb
  app/views/layouts/_header.html.erb
  app/views/layouts/_notifications_dropdown.html.erb
  app/views/participants/notifications_message.html.erb
  config/routes.rb
  spec/services/notification_service_spec.rb
Labels: Review / Feedback Needed

#1562 Fix params in CalculateLeaderboardJob
  app/jobs/calculate_leaderboard_job.rb
  app/services/notification_service.rb
Labels: Review / Feedback Needed, bug

#1564 Fix nil exception on score or score_secondary
  app/services/challenge_rounds/create_leaderboards_service.rb
  spec/services/challenge_rounds/create_leaderboards_service_spec.rb
Labels: Review / Feedback Needed

#1561 Add UUID suffix to Eua files
  app/uploaders/eua_uploader.rb
  app/uploaders/participant_eua_uploader.rb
Labels: Review / Feedback Needed

#1565 Fix featured sequence default value
  db/migrate/20200615135036_change_challenge_featured_sequence_default.rb
  db/schema.rb
Labels: Review / Feedback Needed

#1556 Include Gitlab activity in activity heatmap
  app/controllers/participants_controller.rb
  app/queries/participants/activity_query.rb
  app/services/gitlab/fetch_calendar_activity_service.rb
  app/services/participants/activity_heatmap_service.rb
  spec/controllers/participants_controller_spec.rb
  spec/features/participants/email_preferences_spec.rb
  spec/features/participants/profile_fields_visibility_spec.rb
  spec/queries/participants/activity_query_spec.rb
  spec/services/gitlab/fetch_calendar_activity_service_spec.rb
  spec/services/participants/activity_heatmap_service_spec.rb
  spec/vcr/gitlab_api/fetch_calendar_activity/failure.yml
  spec/vcr/gitlab_api/fetch_calendar_activity/success.yml
Labels: Review / Feedback Needed

#1563 Update github omniauth requested permissions
  app/controllers/participants/omniauth_callbacks_controller.rb
  app/models/participant.rb
  config/initializers/devise.rb
Labels: Review / Feedback Needed

#1568 Fix recent Rollbar errors
  app/controllers/leaderboards_controller.rb
  app/queries/submissions_remaining_query.rb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/participants/_get_user_profile.html.erb
Labels: Review / Feedback Needed, bug

#1575 Don't raise exception when participant is invalid in github oauth
  app/controllers/participants/omniauth_callbacks_controller.rb
Labels: bug

#1576 Fix infinite scroll issue for submissions
  app/assets/stylesheets/application-redesign.css.scss
  app/views/submissions/index.html.erb
Labels: Review / Feedback Needed

#1577 Fix leaderboard filter query issue
  app/policies/leaderboard_policy.rb
  app/policies/ongoing_leaderboard_policy.rb
  app/services/leaderboards/filter_service.rb
  spec/services/leaderboards/filter_service.rb
Labels: Review / Feedback Needed

#1578 Fix Gitlab::FetchCalendarActivityService JSON::ParserError
  Gemfile
  Gemfile.lock
  app/services/gitlab/fetch_calendar_activity_service.rb
  spec/services/gitlab/fetch_calendar_activity_service_spec.rb
  spec/vcr/gitlab_api/fetch_calendar_activity/not_found.yml
  spec/vcr/gitlab_api/fetch_calendar_activity/redirect.yml
  spec/vcr/gitlab_api/fetch_calendar_activity/success.yml
  spec/vcr/gitlab_api/fetch_calendar_activity/unauthorized.yml
Labels: Review / Feedback Needed, bug

#1579 Fix submissions remaining message
  app/views/submissions/index.html.erb
Labels: Review / Feedback Needed

#1238 Install dalli Memcache client
  Gemfile
  Gemfile.lock
  config/environments/production.rb
  config/environments/staging.rb
Labels: Review / Feedback Needed

#1582 Fix review apps failing on foreign key constraints
  app.json
Labels: bug

#1581 Fix participant submissions for meta challenge
  app/controllers/submissions_controller.rb
Labels: Review / Feedback Needed

#1584 Fix EUA files suffix issue
  app/uploaders/eua_uploader.rb
  app/uploaders/participant_eua_uploader.rb
Labels: Review / Feedback Needed, bug

#1589 Case insensitive organizer member adding by e-mail
  app/controllers/members_controller.rb
Labels: Review / Feedback Needed, bug

#1583 Move Paloma Controllers to StimulusJs
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/controllers/challenges_controller.js
  app/assets/javascripts/controllers/dataset_files_controller.js
  app/assets/javascripts/controllers/email_preferences_controller.js
  app/assets/javascripts/controllers/leaderboards_controller.js
  app/assets/javascripts/controllers/participants_controller.js
  app/assets/javascripts/controllers/task_dataset_files_controller.js
  app/assets/javascripts/modules/challenges.js
  app/assets/javascripts/modules/social_share.js
  app/assets/javascripts/pages/email_preferences_edit.js
  app/assets/javascripts/pages/participants_edit.js
  app/javascript/stimulus_js/controllers/challenges_controller.js
  app/javascript/stimulus_js/controllers/challenges_edit_controller.js
  app/javascript/stimulus_js/controllers/challenges_reorder_controller.js
  app/javascript/stimulus_js/controllers/copy_link_controller.js
  app/javascript/stimulus_js/controllers/dataset_files_form_controller.js
  app/javascript/stimulus_js/controllers/email_preferences_controller.js
  app/javascript/stimulus_js/controllers/leaderboard_controller.js
  app/javascript/stimulus_js/controllers/leaderboards_controller.js
  app/javascript/stimulus_js/controllers/rating_progression_controller.js
  app/javascript/stimulus_js/controllers/task_dataset_files_controller.js
  app/javascript/stimulus_js/helpers/videos_helper.js
  app/views/challenges/edit.html.erb
  app/views/challenges/reorder.html.erb
  app/views/challenges/update.js.erb
  app/views/dataset_files/_form.html.erb
  app/views/email_preferences/_form.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/error.html.erb
  app/views/leaderboards/_filter_leaderboards.html.erb
  app/views/leaderboards/index.html.erb
  app/views/leaderboards/index.js.erb
  app/views/leaderboards/show.html.erb
  app/views/participants/show.html.erb
  app/views/submissions/show.html.erb
  app/views/task_dataset_files/index.html.erb
Labels: Review / Feedback Needed

#1596 Fix organization member tooltip issue
  app/views/members/_members.html.erb
Labels: Review / Feedback Needed

#1585 Prevent to create notification with existing notfication message
  app/models/concerns/polymorphic_submitter.rb
  app/services/notification_service.rb
  lib/tasks/remove_notification.rake
Labels: Review / Feedback Needed

#1594 Fix TaskDatasetFilesController#index Rollbar error
  app/controllers/task_dataset_files_controller.rb
Labels: Review / Feedback Needed, bug

#1593 Change default image for challenge
  app/assets/images/challenges/AIcrowd-ProblemStatements-0.jpeg
  app/assets/images/challenges/AIcrowd-ProblemStatements-1.jpeg
  app/helpers/meta_tags_helper.rb
  app/models/challenge.rb
  app/services/images/base64_encode_service.rb
  app/uploaders/image_uploader.rb
  app/uploaders/logo_image_uploader.rb
  app/views/challenges/tabs/_details_form.html.erb
  app/views/participants/_challenge_list.html.erb
  app/views/shared/challenges/_listing.html.erb
  app/views/shared/challenges/_listing_compact.html.erb
  spec/requests/challenges_controller_spec.rb
  spec/serializers/export/challenge_serializer_spec.rb
  spec/vcr/images/base64_encode_service/default_challenge_image_success.yml
Labels: Review / Feedback Needed

#1590 Fix missing forms errors across website
  app/controllers/challenge_call_responses_controller.rb
  app/controllers/challenges_controller.rb
  app/controllers/clef_tasks_controller.rb
  app/controllers/organizers_controller.rb
  app/controllers/submissions_controller.rb
  app/controllers/task_dataset_files_controller.rb
  app/views/challenge_call_responses/_call_closed.html.erb
  app/views/challenge_call_responses/_call_open.html.erb
  app/views/challenge_problems/_form.html.erb
  app/views/challenge_rules/show.html.erb
  app/views/challenges/_form.html.erb
  app/views/challenges/newsletter_emails/new.html.erb
  app/views/clef_tasks/_form.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/organizers/_form.html.erb
  app/views/participants/edit.html.erb
  app/views/submissions/edit.html.erb
  app/views/submissions/new/_artifact.html.erb
  app/views/submissions/new/_clef_form.html.erb
  app/views/submissions/new/_code.html.erb
  app/views/task_dataset_files/_form.html.erb
Labels: Review / Feedback Needed

#1599 Fix schema.rb and seeds.rb files
  db/schema.rb
  db/seeds.rb
Labels: Review / Feedback Needed, bug

#1588 Add AWS credentials validations for dataset files and dataset folders
  app/controllers/dataset_files_controller.rb
  app/controllers/dataset_folders_controller.rb
  app/javascript/stimulus_js/controllers/dataset_files_form_controller.js
  app/services/aws/base_service.rb
  app/services/aws/fetch_dataset_file_service.rb
  app/views/dataset_files/_form.html.erb
  app/views/dataset_folders/_form.html.erb
  spec/services/aws/fetch_dataset_file_service_spec.rb
  spec/vcr/aws_api/fetch_dataset_file/invalid_api_keys.yml
  spec/vcr/aws_api/fetch_dataset_file/invalid_parameters.yml
  spec/vcr/aws_api/fetch_dataset_file/success.yml
Labels: Review / Feedback Needed

#1598 Add submission_file validation to submissions#new form
  app/controllers/submissions_controller.rb
Labels: Review / Feedback Needed

#1600 Fix notification bell icon issue
  app/helpers/application_helper.rb
  app/javascript/stimulus_js/controllers/notifications_controller.js
  app/views/layouts/_header.html.erb
  app/views/layouts/_notifications_dropdown.html.erb
  app/views/participants/read_notification.js.erb
Labels: Review / Feedback Needed

#1607 Add practice_flag to challenge import white list
  app/models/concerns/challenges/import_constants.rb
Labels: Review / Feedback Needed
