Repository AIcrowd/AIcrowd, pull requests merged in 2020-05, with the labels that each got.

#1397 set sidebar with truncate
  app/assets/stylesheets/application-redesign.css.scss
  app/helpers/challenges_helper.rb
  app/views/challenges/discussions/show.html.erb
  app/views/challenges/show/_baseline_discussions.html.erb
  app/views/challenges/show/_latest_five_submissions.html.erb
  app/views/challenges/show/_sidenav.html.erb
  app/views/challenges/show/_top_five_leaderboards.html.erb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/leaderboards/index.html.erb
  app/views/leaderboards/index.js.erb
  app/views/participants/_name_avatar.html.erb
  app/views/submissions/_submissions.html.erb
  app/views/submissions/index.html.erb
  app/views/submissions/index.js.erb
Labels: Review / Feedback Needed

#1409 Undo removal of verify_ssl=False, the endpoint is not yet stable
  config/initializers/evaluations_api.rb
Labels: Review / Feedback Needed

#1413 Changed scoring formula to weighted sum for meta challenge
  app/services/calculate_meta_leaderboard_service.rb
Labels: Review / Feedback Needed

#1412 Feature/Challenge Banner
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/challenges_controller.rb
  app/controllers/leaderboards_controller.rb
  app/models/challenge.rb
  app/models/concerns/challenges/import_constants.rb
  app/policies/challenge_policy.rb
  app/serializers/export/challenge_serializer.rb
  app/services/challenges/import_service.rb
  app/views/challenges/show/_sidenav.html.erb
  app/views/challenges/tabs/_details_form.html.erb
  app/views/shared/challenges/_masthead.html.erb
  app/views/shared/challenges/_masthead_extra.html.erb
  app/views/shared/challenges/_masthead_pills.html.erb
  config/routes.rb
  db/migrate/20200501225322_add_banner_file_to_challenge.rb
  db/migrate/20200502001504_add_banner_color_to_challenge.rb
  db/schema.rb
Labels: Review / Feedback Needed

#1416 Feature/challenge listing v2 + Challenge pill bugfix for meta challenge + Mobile views
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/challenges_controller.rb
  app/models/challenge.rb
  app/models/concerns/challenges/import_constants.rb
  app/uploaders/image_uploader.rb
  app/views/challenges/tabs/_details_form.html.erb
  app/views/shared/challenges/_listing.html.erb
  app/views/shared/challenges/_listing_compact.html.erb
  app/views/shared/challenges/_masthead.html.erb
  app/views/shared/challenges/_masthead_extra.html.erb
  app/views/shared/challenges/_masthead_pills.html.erb
  config/routes.rb
  db/migrate/20200502125205_add_big_challenge_card_image_to_challenge.rb
  db/migrate/20200502142113_add_banner_mobile_file_to_challenge.rb
  db/schema.rb
  spec/factories/challenge_factory.rb
Labels: Review / Feedback Needed

#1393 manage banner to admin
  app/admin/setting.rb
  app/assets/stylesheets/application-redesign.css.scss
  app/helpers/application_helper.rb
  app/models/setting.rb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  db/migrate/20200428141610_add_banner_to_setting.rb
  db/schema.rb
Labels: Review / Feedback Needed

#1401 Do not show draft challenges on organizers#show page for not logged u…
  app/controllers/organizers_controller.rb
Labels: Review / Feedback Needed

#1419 Urgent Bugfix: Challenge Problem mapping made admin-only till proper fix
  app/controllers/challenge_problems_controller.rb
  app/policies/challenge_problems_policy.rb
Labels: Review / Feedback Needed

#1421 Removed height value in truncate class
  app/assets/stylesheets/application-redesign.css.scss
Labels: Review / Feedback Needed

#1420 Hide badge reputation on participant masthead & link to leaderboards
  app/views/landing_page/index.html.erb
  app/views/layouts/_header.html.erb
  app/views/participants/_masthead.html.erb
  spec/features/challenges/participant_challenge_spec.rb
Labels: Review / Feedback Needed

#1399 Quick fix
  app/views/participant_challenges/_participant_challenge_rows.erb
Labels: Review / Feedback Needed

#1398 Remove gap below stats
  app/assets/stylesheets/application-redesign.css.scss
  app/views/shared/challenges/_listing.html.erb
Labels: Review / Feedback Needed

#1423 Bugfix/meta challenge
  app/helpers/challenges_helper.rb
  app/models/challenge.rb
  app/views/challenges/show/_subnav.html.erb
  app/views/insights/_charts/_submissions_vs_time.html.erb
  app/views/insights/_charts/_top_score_vs_time.html.erb
  app/views/submissions/_submissions.html.erb
Labels: Review / Feedback Needed

#1426 Added geeks view for meta challenge leaderboard
  app/assets/javascripts/controllers/leaderboards_controller.js
  app/controllers/insights_controller.rb
  app/controllers/leaderboards_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/leaderboard_helper.rb
  app/services/calculate_meta_leaderboard_service.rb
  app/views/insights/_charts/_top_score_vs_time.html.erb
  app/views/insights/index.html.erb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/leaderboards/index.html.erb
Labels: Review / Feedback Needed

#1434 Change URL of challenge rules to not require :id
  app/controllers/challenge_rules_controller.rb
  app/controllers/dataset_files_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/challenges_helper.rb
  app/views/challenge_rules/show.html.erb
  app/views/challenges/show/_subnav.html.erb
  config/routes.rb
Labels: Review / Feedback Needed

#1424 Change banner_text type to admin
  app/admin/setting.rb
  app/helpers/application_helper.rb
  app/views/layouts/_footer.html.erb
  db/migrate/20200504111847_change_banner_text_to_be_text_in_settings.rb
  db/schema.rb
Labels: Review / Feedback Needed

#1436 Changed leaderboard computation to provide same rank for same scores
  app/services/calculate_leaderboard_service.rb
  spec/services/calculate_leaderboard_same_rank_spec.rb
Labels: Review / Feedback Needed

#1437 Redo geek view rendering upon load more
  app/assets/javascripts/controllers/leaderboards_controller.js
  app/views/leaderboards/index.js.erb
Labels: Review / Feedback Needed

#1432 Truncate user name on specific places
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/api/v1/participants_controller.rb
  app/javascript/stimulus_js/controllers/participants_controller.js
  app/views/challenges/show/_latest_five_submissions.html.erb
  app/views/challenges/show/_top_five_leaderboards.html.erb
  app/views/landing_page/_discourse_top_contributors.html.erb
  app/views/landing_page/index.html.erb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/participants/_get_user_profile.html.erb
  app/views/participants/_name_avatar.html.erb
  app/views/participants/_user_link.html.erb
Labels: Review / Feedback Needed

#1429 Add calendar heatmap to user profile
  app/assets/stylesheets/application-redesign.css.scss
  app/assets/stylesheets/participants/activity_heatmap.scss
  app/controllers/participants_controller.rb
  app/javascript/stimulus_js/controllers/activity_heatmap_controller.js
  app/queries/participants/activity_query.rb
  app/views/participants/show.html.erb
  package.json
  spec/factories/ahoy/visit_factory.rb
  spec/queries/participants/activity_query_spec.rb
  yarn.lock
Labels: Review / Feedback Needed

#1430 Fix newsletter_email query that checks permissions
  app/mailers/organizers/newsletter_email_mailer.rb
Labels: Review / Feedback Needed

#1435 Redirect after participants accepts terms to previous page
  app/controllers/application_controller.rb
  app/controllers/challenge_participants_controller.rb
Labels: Review / Feedback Needed

#1425 Implement infinite scroll
  app/assets/stylesheets/application-redesign.css.scss
  app/javascript/stimulus_js/controllers/challenges_controller.js
  app/javascript/stimulus_js/controllers/load_more_controller.js
  app/views/challenges/index.html.erb
  app/views/challenges/index.js.erb
  app/views/leaderboards/index.html.erb
  app/views/leaderboards/index.js.erb
  app/views/participant_challenges/_participant_challenges.html.erb
  app/views/participant_challenges/index.js.erb
  app/views/rating_leaderboard/index.html.erb
  app/views/rating_leaderboard/index.js.erb
  app/views/submissions/index.html.erb
  app/views/submissions/index.js.erb
Labels: Review / Feedback Needed

#1441 Add submission link to leaderboards and submissions
  app/assets/images/img/code_snippet.svg
  app/controllers/submissions_controller.rb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/leaderboards/index.html.erb
  app/views/submissions/_submissions.html.erb
  app/views/submissions/edit.html.erb
  app/views/submissions/index.html.erb
  app/views/submissions/new/_artifact.html.erb
  app/views/submissions/new/_clef_form.html.erb
  app/views/submissions/show.html.erb
  db/migrate/20200507164323_add_submission_link_to_submissions.rb
Labels: Review / Feedback Needed

#1433 Show number of team statistic
  app/helpers/challenges_helper.rb
  app/models/challenge.rb
  app/views/shared/challenges/_listing.html.erb
  app/views/shared/challenges/_masthead_extra.html.erb
  app/views/shared/challenges/_team_stat.html.erb
Labels: Review / Feedback Needed

#1444 Truncate team name
  app/views/challenges/show/_sidenav.html.erb
  app/views/challenges/show/_top_five_leaderboards.html.erb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/leaderboards/index.html.erb
Labels: Review / Feedback Needed

#1439 Set default 1 for challenge featured_sequence
  app/helpers/challenges_helper.rb
  app/models/challenge.rb
  app/views/challenges/tabs/_details_form.html.erb
  db/migrate/20200507094530_change_challenge_default.rb
  db/schema.rb
  lib/tasks/update_featured_sequence.rake
Labels: Review / Feedback Needed

#1447 Feature: Leaderboard recomputations on challenge update
  app/controllers/challenges_controller.rb
Labels: Review / Feedback Needed

#1449 Suggestion: Infinite scroll trigger condition
  app/javascript/stimulus_js/controllers/load_more_controller.js
Labels: Review / Feedback Needed

#1404 Update dataset files new form
  app/controllers/dataset_files_controller.rb
  app/views/dataset_files/_form.html.erb
  app/views/dataset_files/edit.html.erb
  app/views/dataset_files/new.html.erb
  app/views/shared/challenges/_dataset_file.html.erb
  db/migrate/20200501103734_add_own_s3_columns_to_dataset_files.rb
  db/schema.rb
Labels: Review / Feedback Needed

#1407 Remove application-old.html.erb and bare.html.erb layouts from codebase
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/_404.scss
  app/assets/stylesheets/_additions.scss
  app/assets/stylesheets/_article.scss
  app/assets/stylesheets/_badges.scss
  app/assets/stylesheets/_buttons.scss
  app/assets/stylesheets/_cookies.scss
  app/assets/stylesheets/_detail.scss
  app/assets/stylesheets/_doorkeeper.scss
  app/assets/stylesheets/_dropdowns.scss
  app/assets/stylesheets/_flag-core.scss
  app/assets/stylesheets/_flag-list.scss
  app/assets/stylesheets/_flex-grid.scss
  app/assets/stylesheets/_footer.scss
  app/assets/stylesheets/_forms.scss
  app/assets/stylesheets/_header.scss
  app/assets/stylesheets/_home-hero.scss
  app/assets/stylesheets/_inline_validations.scss
  app/assets/stylesheets/_layout-atoms.scss
  app/assets/stylesheets/_layout-molecules.scss
  app/assets/stylesheets/_loader.scss
  app/assets/stylesheets/_markdown.scss
  app/assets/stylesheets/_mastheads.scss
  app/assets/stylesheets/_md-editor.scss
  app/assets/stylesheets/_pagination-dots.scss
  app/assets/stylesheets/_panel.scss
  app/assets/stylesheets/_progress-bar.scss
  app/assets/stylesheets/_remodal-default-theme.scss
  app/assets/stylesheets/_reset.scss
  app/assets/stylesheets/_responsive-iframe.scss
  app/assets/stylesheets/_search.scss
  app/assets/stylesheets/_section-header.scss
  app/assets/stylesheets/_subnav_tabs.scss
  app/assets/stylesheets/_tables.scss
  app/assets/stylesheets/_typography.scss
  app/assets/stylesheets/_utilities.scss
  app/assets/stylesheets/application.css.scss
  app/controllers/dataset_files_controller.rb
  app/views/layouts/_footer_old.html.erb
  app/views/layouts/_header_old.html.erb
  app/views/layouts/_search.html.erb
  app/views/layouts/application-old.html.erb
  app/views/layouts/bare.html.erb
  vendor/assets/stylesheets/notebook.css
  vendor/assets/stylesheets/prism.css
Labels: Review / Feedback Needed

#1452 Remove precompilation of application.css from sprockets
  app/assets/config/manifest.js
  db/schema.rb
Labels: bug

#1451 Reduce web server memory usage
  Gemfile
  Gemfile.lock
  config/initializers/puma_worker_killer.rb
  config/puma.rb
Labels: Review / Feedback Needed

#1457 Set new order from 1
  app/controllers/challenges_controller.rb
Labels: Review / Feedback Needed

#1450 Fix space after teams count
  app/assets/stylesheets/application-redesign.css.scss
  app/views/shared/challenges/_masthead_extra.html.erb
  app/views/shared/challenges/_team_stat.html.erb
Labels: Review / Feedback Needed

#1462 Fix 5xx error in submissions CSV download
  app/admin/submission.rb
Labels: Review / Feedback Needed, bug

#1460 set thumb media content type
  app/helpers/media_helper.rb
  app/views/shared/challenges/_media.html.erb
Labels: Review / Feedback Needed

#1453 Choose random default image
  app/assets/images/users/AIcrowd-DarkerBG (0).png
  app/assets/images/users/AIcrowd-DarkerBG (1).png
  app/assets/images/users/AIcrowd-DarkerBG (2).png
  app/assets/images/users/AIcrowd-DarkerBG (3).png
  app/assets/images/users/AIcrowd-DarkerBG (4).png
  app/assets/images/users/AIcrowd-DarkerBG (5).png
  app/assets/images/users/AIcrowd-DarkerBG (6).png
  app/assets/images/users/AIcrowd-DarkerBG (7).png
  app/controllers/participants_controller.rb
  app/helpers/images_helper.rb
  app/helpers/meta_tags_helper.rb
  app/models/participant.rb
  app/uploaders/image_uploader.rb
  app/uploaders/logo_image_uploader.rb
  app/views/challenges/fields/_challenge_partner_fields.html.erb
  spec/services/discourse/fetch_top_contributors_service_spec.rb
Labels: Review / Feedback Needed

#1456 Remove useless gems
  Gemfile
  Gemfile.lock
Labels: Review / Feedback Needed

#1454 Add Api::V1::DatasetFiles#create #update and #destroy endpoints
  app/controllers/api/v1/challenges/dataset_files_controller.rb
  app/serializers/api/v1/dataset_file_serializer.rb
  config/routes.rb
  spec/requests/api/v1/challenges/dataset_files_controller_spec.rb
  spec/serializers/api/v1/dataset_file_serializer_spec.rb
Labels: Review / Feedback Needed

#1459 Add DatasetFolder#create #update and #destroy endpoints
  app/controllers/api/v1/challenges/dataset_folders_controller.rb
  app/helpers/images_helper.rb
  app/serializers/api/v1/dataset_folder_serializer.rb
  config/routes.rb
  db/schema.rb
  spec/requests/api/v1/challenges/dataset_folders_controller_spec.rb
  spec/serializers/api/v1/dataset_folder_serializer_spec.rb
  spec/services/aws/fetch_dataset_files_service_spec.rb
Labels: Review / Feedback Needed

#1403 Practice challenge feature
  app/admin/challenge.rb
  app/admin/challenges.rb
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/challenges_controller.rb
  app/controllers/practices_controller.rb
  app/models/challenge.rb
  app/views/challenges/index.html.erb
  app/views/challenges/show_meta_challenge.html.erb
  app/views/challenges/tabs/_admin_form.html.erb
  app/views/layouts/_header.html.erb
  app/views/practices/index.html.erb
  app/views/shared/challenges/_filter.html.erb
  app/views/shared/challenges/_listing_compact.html.erb
  app/views/shared/challenges/_masthead_pills.html.erb
  config/routes.rb
  db/migrate/20200430075432_add_practice_flag_to_challenge.rb
  db/migrate/20200508170915_add_editors_selection_to_challenge.rb
  db/schema.rb
Labels: Review / Feedback Needed

#1461 Add own_s3 fields to dataset_files
  app/assets/javascripts/controllers/dataset_files_controller.js
  app/assets/stylesheets/challenges/dataset_files.scss
  app/controllers/api/v1/challenges/dataset_files_controller.rb
  app/controllers/dataset_files_controller.rb
  app/helpers/files_helper.rb
  app/models/concerns/challenges/import_constants.rb
  app/models/dataset_file.rb
  app/services/aws/base_service.rb
  app/services/aws/fetch_dataset_file_service.rb
  app/services/aws/fetch_dataset_folder_service.rb
  app/views/dataset_files/_form.html.erb
  app/views/shared/challenges/_dataset_file.html.erb
  db/migrate/20200513101320_add_own_s3_fields_to_dataset_files.rb
  db/schema.rb
  spec/services/aws/fetch_dataset_file_service_spec.rb
  spec/services/aws/fetch_dataset_folder_service_spec.rb
  spec/vcr/aws_api/fetch_dataset_file/failure.yml
  spec/vcr/aws_api/fetch_dataset_file/success.yml
  spec/vcr/aws_api/fetch_dataset_folder/failure.yml
  spec/vcr/aws_api/fetch_dataset_folder/success.yml
Labels: Review / Feedback Needed

#1464 Update practices route to practice
  app/controllers/practice_controller.rb
  app/views/layouts/_header.html.erb
  app/views/practice/index.html.erb
  app/views/shared/challenges/_listing_compact.html.erb
  config/routes.rb
Labels: Review / Feedback Needed

#1468 practice banner link to challenge show
  app/views/shared/challenges/_listing_compact.html.erb
Labels: Review / Feedback Needed

#1465 Implement activity heatmap feedback
  app/assets/stylesheets/participants/activity_heatmap.scss
  app/controllers/participants_controller.rb
  app/helpers/graphs_helper.rb
  app/javascript/stimulus_js/controllers/activity_heatmap_controller.js
  app/views/participants/show.html.erb
  package.json
  yarn.lock
Labels: Review / Feedback Needed

#1470 Set heading for practice editors selection
  app/assets/stylesheets/application-redesign.css.scss
  app/views/practice/index.html.erb
Labels: Review / Feedback Needed

#1475 Bugfix/image 0x0 ckeditor
  app/assets/javascripts/ckeditor/plugins/markdown/plugin.js
Labels: Review / Feedback Needed

#1474 Bringing back baseline submission entries back to life
  app/assets/stylesheets/application-redesign.css.scss
  app/views/leaderboards/_leaderboards.html.erb
  app/views/submissions/edit.html.erb
  app/views/submissions/show.html.erb
Labels: Review / Feedback Needed

#1472 Fix undefined_method exception of TaskDatasetFile objects
  app/models/task_dataset_file.rb
Labels: Review / Feedback Needed, bug

#1477 Return 404 not found page when challenge rules are missing
  app/controllers/challenge_rules_controller.rb
  app/models/participant_organizer.rb
Labels: bug

#1481 Add missing external_file_size field to dataset_files form
  app/controllers/dataset_files_controller.rb
  app/helpers/files_helper.rb
  app/views/dataset_files/_form.html.erb
Labels: Review / Feedback Needed

#1489 Don't show baselines in top 5 leaderboard entries
  app/controllers/challenges_controller.rb
Labels: Review / Feedback Needed

#1487 Fix organisation new member form
  app/controllers/members_controller.rb
Labels: Review / Feedback Needed, bug

#1488 Don't raise error when users are already members of Discourse group
  app/services/discourse/add_users_to_group_service.rb
Labels: Review / Feedback Needed, bug

#1491 Added option to hide secondary score in leaderboards
  app/models/challenge_round.rb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/leaderboards/index.html.erb
Labels: Review / Feedback Needed

#1492 Bugfix: width of image and table in md-content rendering
  app/assets/stylesheets/application-redesign.css.scss
Labels: Review / Feedback Needed

#1483 Truncate submission message
  app/assets/stylesheets/application-redesign.css.scss
  app/views/submissions/_submissions.html.erb
  app/views/submissions/show.html.erb
Labels: Review / Feedback Needed

#1497 Remove prizes information from challenges in user insights tab
  app/views/participants/_challenge_list.html.erb
Labels: Review / Feedback Needed

#1495 Remove decoration from section headers
  app/views/challenges/show_meta_challenge.html.erb
  app/views/insights/_charts/_challenge_participants_country.html.erb
  app/views/insights/_charts/_submissions_vs_time.html.erb
  app/views/insights/_charts/_top_score_vs_time.html.erb
  app/views/landing_page/index.html.erb
  app/views/participants/show.html.erb
  app/views/submissions/new/_choose.html.erb
Labels: Review / Feedback Needed

#1478 Add multiselect to newsletter_emails form
  app/controllers/api/v1/challenges/newsletter_emails_controller.rb
  app/controllers/api/v1/challenges/participants_controller.rb
  app/controllers/api/v1/challenges/teams_controller.rb
  app/controllers/challenges/newsletter_emails_controller.rb
  app/forms/newsletter_email_form.rb
  app/serializers/api/v1/challenges/search_newsletter_emails_serializer.rb
  app/serializers/api/v1/challenges/search_participants_serializer.rb
  app/serializers/api/v1/challenges/search_teams_serializer.rb
  app/views/challenges/newsletter_emails/new.html.erb
  config/routes.rb
  spec/features/newsletter_emails_controller_spec.rb
  spec/requests/api/v1/challenges/newsletter_emails_controller_spec.rb
  spec/requests/api/v1/challenges/participants_controller_spec.rb
  spec/requests/api/v1/challenges/teams_controller_spec.rb
  spec/serializers/api/v1/challenges/search_newsletter_email_serializer_spec.rb
  spec/serializers/api/v1/challenges/search_participants_serializer_spec.rb
  spec/serializers/api/v1/challenges/search_teams_serializer_spec.rb
Labels: Review / Feedback Needed

#1502 Fix bcc field for Admin::NewsletterEmailNotificationMailer email
  app/mailers/admin/newsletter_email_notification_mailer.rb
Labels: bug

#1494 Fix SubmissionRemainingQuery nil exception
  app/queries/submissions_remaining_query.rb
Labels: Review / Feedback Needed, bug

#1479 Fix prefixed hash category filter issue
  app/controllers/challenges_controller.rb
  app/helpers/challenges_helper.rb
  app/models/category.rb
  lib/tasks/categories.rake
Labels: Review / Feedback Needed

#1499 Fix decoration header for remaining places
  app/views/challenges/show/_baseline_discussions.html.erb
  app/views/challenges/show/_latest_five_submissions.html.erb
  app/views/challenges/show/_sidenav.html.erb
  app/views/challenges/show/_top_five_leaderboards.html.erb
Labels: Review / Feedback Needed

#1503 featured_sequence value default on challenge count
  app/helpers/challenges_helper.rb
Labels: Review / Feedback Needed

#1501 Tooltip and Achievements UI implementation, Toast and Badge Type implementation
  app/admin/badge_types.rb
  app/assets/images/img/icon-achievement-bronze.svg
  app/assets/images/img/icon-achievement-gold.svg
  app/assets/images/img/icon-achievement-silver.svg
  app/assets/javascripts/application.js
  app/assets/stylesheets/application-redesign.css.scss
  app/models/aicrowd_badge.rb
  app/models/aicrowd_user_badge.rb
  app/models/badge_type.rb
  app/models/participant.rb
  app/views/layouts/application.html.erb
  app/views/participants/_achievements.erb
  app/views/participants/_badges_list.html.erb
  app/views/participants/_tooltip_profile.html.erb
  app/views/participants/show.html.erb
  db/migrate/20200522135605_add_toast_shown_to_aicrowd_user_badge.rb
  db/schema.rb
Labels: Review / Feedback Needed

#1506 Practice badge on profile and organizers challenge list
  app/views/participants/_challenge_list.html.erb
  app/views/shared/challenges/_listing.html.erb
Labels: Review / Feedback Needed
