Repository AIcrowd/AIcrowd, pull requests merged in 2020-04, with the labels that each got.

#1291 Api to check user login
  app/controllers/api/v1/sessions/helpers_controller.rb
  app/services/session_service.rb
  config/initializers/session_store.rb
  config/routes.rb
Labels: Review / Feedback Needed

#1307 Capitalise links in table of content
  app/assets/stylesheets/application-redesign.css.scss
Labels: Review / Feedback Needed, bug

#1305 Reverted tabular table of content
  app/javascript/stimulus_js/controllers/challenge_overview_controller.js
Labels: Review / Feedback Needed

#1306 Fix leaderboard rendering for single person team
  app/views/leaderboards/_leaderboards.html.erb
Labels: Review / Feedback Needed

#1304 Added reCaptcha during signups to prevent bot signups
  Gemfile
  Gemfile.lock
  app/controllers/participants/registrations_controller.rb
  app/views/devise/registrations/new.html.erb
  config/application.yml.example
  config/routes.rb
Labels: Enhancement / Feature, Review / Feedback Needed

#1317 Adding blog link in the leaderboard page
  app/views/rating_leaderboard/index.html.erb
Labels: Review / Feedback Needed

#1299 Handle invalid credentials in Discourse services
  app/services/discourse/base_service.rb
  app/services/discourse/create_category_service.rb
  app/services/discourse/fetch_challenge_topics_service.rb
  app/services/discourse/fetch_latest_topics_service.rb
  app/services/discourse/fetch_top_contributors_service.rb
  app/services/discourse/fetch_user_posts_service.rb
  app/services/discourse/update_category_service.rb
  spec/services/discourse/create_category_service_spec.rb
  spec/services/discourse/fetch_challenge_topics_service_spec.rb
  spec/services/discourse/fetch_latest_topics_service_spec.rb
  spec/services/discourse/fetch_top_contributors_service_spec.rb
  spec/services/discourse/fetch_user_posts_service_spec.rb
  spec/services/discourse/update_category_service_spec.rb
Labels: Review / Feedback Needed

#1319 Fix challenge_round removal
  app/controllers/api/v1/base_controller.rb
  app/controllers/api/v1/challenges/challenge_rounds_controller.rb
  app/controllers/challenges_controller.rb
  app/javascript/stimulus_js/controllers/challenge_rounds_controller.js
  app/javascript/stimulus_js/controllers/newsletter_email_form_controller.js
  app/javascript/stimulus_js/helpers/alerts_helper.js
  app/javascript/stimulus_js/helpers/buttons_helper.js
  app/models/challenge.rb
  app/models/challenge_round.rb
  app/views/challenges/fields/_challenge_round_fields.html.erb
  config/routes.rb
  spec/requests/api/v1/challenges/challenge_rounds_controller_spec.rb
Labels: Review / Feedback Needed

#1321 Fix CKeditor on newsletter_emails#new page
  app/assets/stylesheets/challenges/newsletter_email_form.scss
  app/javascript/stimulus_js/controllers/newsletter_email_form_controller.js
  app/views/challenges/newsletter_emails/new.html.erb
  app/views/challenges/tabs/_details_form.html.erb
  app/views/layouts/application.html.erb
Labels: Review / Feedback Needed

#1332 Minor fix for overview h2 and toc rendering
  app/javascript/stimulus_js/controllers/challenge_overview_controller.js
Labels: Review / Feedback Needed

#1334 Submission Policy Tweak: No submission before round starts
  app/policies/challenge_policy.rb
Labels: Review / Feedback Needed

#1329 Add Api::V1::Challenges#create and Api::V1::Challenges#update endpoints
  app.json
  app/controllers/api/base_controller.rb
  app/controllers/api/v1/base_controller.rb
  app/controllers/api/v1/challenges/challenges_controller.rb
  app/controllers/user_rating_controller.rb
  app/models/challenge.rb
  app/models/concerns/challenges/import_constants.rb
  app/models/participant.rb
  app/policies/challenge_policy.rb
  app/serializers/api/v1/challenge_serializer.rb
  app/services/challenges/import_service.rb
  app/services/grader_service.rb
  config.ru
  config/application.yml.example
  config/routes.rb
  spec/fixtures/files/json/challenge_import.json
  spec/fixtures/files/json/challenge_import_with_errors.json
  spec/requests/api/challenges_controller_spec.rb
  spec/requests/api/external_graders_controller/external_graders_controller_GET_spec.rb
  spec/requests/api/participants_controller_spec.rb
  spec/requests/api/submissions_controller_spec.rb
  spec/requests/api/v1/challenges/challenges_controller_spec.rb
  spec/serializers/api/v1/challenge_serializer_spec.rb
  spec/services/challenges/import_service_spec.rb
Labels: Review / Feedback Needed

#1300 Implementation of Badges
  Gemfile
  Gemfile.lock
  app/assets/images/awards/award-bronze.svg
  app/assets/images/awards/award-empty.svg
  app/assets/images/awards/award-gold.svg
  app/assets/images/awards/award-silver.svg
  app/controllers/participants_controller.rb
  app/jobs/badges_daily_job.rb
  app/jobs/discourse_badges_daily_job.rb
  app/models/discourse_user_badges_metum.rb
  app/models/merit/badge_rules.rb
  app/models/merit/point_rules.rb
  app/models/merit/rank_rules.rb
  app/models/participant.rb
  app/models/submission.rb
  app/services/discourse/fetch_badges_meta_service.rb
  app/services/discourse/fetch_badges_service.rb
  app/services/user_rating_service.rb
  app/views/landing_page/index.html.erb
  app/views/participants/_badges_list.html.erb
  app/views/participants/_masthead.html.erb
  app/views/participants/_show_badges.erb
  app/views/participants/_tooltip_profile.html.erb
  app/views/participants/show.html.erb
  app/views/rating_leaderboard/_rating_leaderboard.html.erb
  config/application.yml.example
  config/initializers/merit.rb
  db/migrate/20200331185208_create_merit_actions.rb
  db/migrate/20200331185209_create_merit_activity_logs.rb
  db/migrate/20200331185210_create_sashes.rb
  db/migrate/20200331185211_create_badges_sashes.rb
  db/migrate/20200331185212_create_scores_and_points.rb
  db/migrate/20200331185327_add_merit_fields_to_participants.rb
  db/migrate/20200404154409_add_assigned_permanent_badges_to_challenge_rounds.rb
  db/migrate/20200409170026_create_discourse_user_badges_meta.rb
  db/schema.rb
Labels: Review / Feedback Needed

#1298 implementation of rollback on end time change for a challenge
  app/jobs/rollback_rating_job.rb
  app/models/challenge_round.rb
  app/services/user_rating_service.rb
Labels: Review / Feedback Needed

#1328 fixing the decay issues
  app/controllers/user_rating_controller.rb
  app/models/participant.rb
  app/queries/participant_rating_ranks_query.rb
Labels: Review / Feedback Needed

#1316 temporary rating implementation
  app/assets/stylesheets/_tooltips.scss
  app/models/participant.rb
  app/views/landing_page/index.html.erb
  app/views/participants/_masthead.html.erb
  app/views/participants/_show_reputation.erb
  app/views/participants/_show_temporary_reputation.erb
  app/views/participants/_tooltip_profile.html.erb
  app/views/rating_leaderboard/_rating_leaderboard.html.erb
Labels: Review / Feedback Needed

#1330 Update Challenges::ImportService to support updating of existing challenges
  app/models/concerns/challenges/import_constants.rb
  app/models/concerns/markdownable.rb
  app/serializers/export/challenge_round_serializer.rb
  app/serializers/export/challenge_serializer.rb
  app/services/challenges/import_service.rb
  spec/requests/api/v1/challenges/challenges_controller_spec.rb
  spec/serializers/export/challenge_round_serializer_spec.rb
  spec/serializers/export/dataset_file_serializer_spec.rb
Labels: Review / Feedback Needed

#1337 Add Api::V1::Challenges::ChallengeRoundsController#create and #update endpoints
  app/controllers/api/v1/challenges/challenge_rounds_controller.rb
  app/serializers/api/v1/challenge_round_serializer.rb
  config/routes.rb
  spec/rails_helper.rb
  spec/requests/api/v1/challenges/challenge_rounds_controller_spec.rb
  spec/serializers/api/v1/challenge_round_serializer_spec.rb
  spec/support/shared_examples/api_v1_authentication_spec.rb
Labels: Review / Feedback Needed

#1339 Allow to choose which way tabs are displayed on Overview page
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/challenges_controller.rb
  app/javascript/stimulus_js/controllers/challenge_overview_controller.js
  app/models/concerns/challenges/import_constants.rb
  app/views/challenges/fields/_fancy_radio.html.erb
  app/views/challenges/show.html.erb
  app/views/challenges/tabs/_overview_form.html.erb
  db/migrate/20200414144802_add_tabular_overview_to_challenges.rb
  db/schema.rb
Labels: Review / Feedback Needed

#1351 Show only 3 blogs on AIcrowd landing page
  app/controllers/landing_page_controller.rb
Labels: Review / Feedback Needed

#1346 Remove ChallengeOrganizerParticipant materialized view
  app/jobs/refresh_challenge_organizer_participant_view_job.rb
  app/models/participant.rb
  app/models/views/challenge_organizer_participants.rb
  app/policies/leaderboard_policy.rb
  db/migrate/20200416102555_drop_challenge_organizer_participants_materialised_view.rb
  db/schema.rb
  db/views/challenge_organizer_participants_v01.sql
  spec/jobs/refresh_challenge_organizer_participant_view_job_spec.rb
Labels: Review / Feedback Needed

#1336 Add version tracking to submissions
  Gemfile
  Gemfile.lock
  app/admin/paper_trail/version.rb
  app/admin/submission.rb
  app/assets/stylesheets/additional_active_admin.css.scss
  app/models/submission.rb
  config/initializers/active_admin.rb
  db/migrate/20200413190411_remove_versions.rb
  db/migrate/20200413190446_create_versions.rb
  db/migrate/20200413190447_add_object_changes_to_versions.rb
  db/schema.rb
Labels: Review / Feedback Needed

#1353 #1347: Fixed login redirection via application controller
  app/controllers/application_controller.rb
Labels: Review / Feedback Needed

#1324 Fixes on Challenge filter
  app/assets/javascripts/controllers/challenges_controller.js
  app/services/challenges/filter_service.rb
  app/views/shared/challenges/_filter.html.erb
  spec/services/challenges/filter_service_spec.rb
Labels: Review / Feedback Needed

#1327 More Changes to tags on challenge pages
  app/helpers/meta_tags_helper.rb
Labels: Review / Feedback Needed

#1335 Prefix Hash and change category to tags
  app/helpers/challenges_helper.rb
  app/helpers/sanitization_helper.rb
  app/views/challenges/tabs/_details_form.html.erb
  app/views/shared/challenges/_filter.html.erb
  app/views/shared/challenges/_listing.html.erb
  app/views/shared/challenges/_masthead.html.erb
Labels: Review / Feedback Needed

#1338 Fix issue of undefine team
  app/views/leaderboards/_leaderboards.html.erb
Labels: Review / Feedback Needed

#1341 Sanitize HTML entities from challenge round close time
  app/helpers/challenges_helper.rb
Labels: Review / Feedback Needed

#1345 Ckeditor integration with ActiveAdmin markdown fields
  app/admin/blog.rb
  app/admin/challenge_call.rb
  app/admin/job_posting.rb
  app/admin/participation_terms.rb
  app/assets/stylesheets/ckeditor.scss
  app/models/blog.rb
  app/models/challenge_call.rb
  app/models/job_posting.rb
  app/models/participation_terms.rb
  config/initializers/active_admin.rb
  db/migrate/20200415125555_remove_column_markdown.rb
  db/schema.rb
  spec/factories/blog_factory.rb
  spec/factories/job_posting_factory.rb
  spec/factories/participation_terms_factory.rb
  spec/models/blog_spec.rb
  spec/models/challenge_call_spec.rb
Labels: Review / Feedback Needed

#1354 Fix recent rollbar bugs
  app/helpers/submissions_helper.rb
  app/queries/participant_rating_ranks_query.rb
  app/views/blogs/_form.html.erb
  app/views/blogs/edit.html.erb
  config/routes.rb
Labels: Review / Feedback Needed

#1355 Allow to edit newsletter_emails in ActiveAdmin
  app/admin/newsletter_email.rb
  app/assets/stylesheets/additional_active_admin.css.scss
Labels: Review / Feedback Needed

#1348 Add Discourse::CreateGroupService
  app/services/discourse/base_service.rb
  app/services/discourse/create_group_service.rb
  db/migrate/20200416205250_add_discourse_group_id_to_challenges.rb
  db/schema.rb
  spec/services/discourse/create_group_service_spec.rb
  spec/vcr/discourse_api/groups/create/success.yml
  spec/vcr/discourse_api/groups/create/success_generated_new_group_name.yml
  spec/vcr/discourse_api/groups/create/success_truncated_group_name.yml
Labels: Review / Feedback Needed

#1349 Remove organizer_id column from challenges
  db/migrate/20200416231141_update_participant_challenges_view_to_version8.rb
  db/migrate/20200416232006_remove_organizer_id_from_challenges.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/spotify/spotify.rb
  db/views/participant_challenges_v08.sql
  lib/tasks/challenges.rake
  spec/features/challenges/edit_challenge_spec.rb
Labels: Review / Feedback Needed

#1363 Remove duplicated code from Discourse ServiceObject classes
  app/services/discourse/base_service.rb
  app/services/discourse/create_category_service.rb
  app/services/discourse/create_group_service.rb
  app/services/discourse/fetch_badges_meta_service.rb
  app/services/discourse/fetch_badges_service.rb
  app/services/discourse/fetch_challenge_topics_service.rb
  app/services/discourse/fetch_latest_topics_service.rb
  app/services/discourse/fetch_top_contributors_service.rb
  app/services/discourse/fetch_user_posts_service.rb
  app/services/discourse/update_category_service.rb
  config/initializers/merit.rb
  spec/services/discourse/create_category_service_spec.rb
  spec/services/discourse/create_group_service_spec.rb
  spec/services/discourse/fetch_challenge_topics_service_spec.rb
  spec/services/discourse/fetch_latest_topics_service_spec.rb
  spec/services/discourse/fetch_top_contributors_service_spec.rb
  spec/services/discourse/fetch_user_posts_service_spec.rb
  spec/services/discourse/update_category_service_spec.rb
  spec/support/shared_examples/discourse_service_object_spec.rb
Labels: Review / Feedback Needed

#1365 Remove Rubocop checks from Travis
  .travis.yml
Labels: Review / Feedback Needed

#1352 Add Discourse::AddUsersToGroupService
  app/services/discourse/add_users_to_group_service.rb
  app/services/discourse/api_client.rb
  spec/services/discourse/add_users_to_group_service_spec.rb
  spec/vcr/discourse_api/add_users_to_group/failure_username_already_part_of_the_group.yml
  spec/vcr/discourse_api/add_users_to_group/failure_username_does_not_exist_in_discourse.yml
  spec/vcr/discourse_api/add_users_to_group/success.yml
Labels: Review / Feedback Needed

#1368 Fix Discourse API request limit issue
  app/jobs/discourse/create_category_job.rb
  app/jobs/discourse/update_category_job.rb
  app/models/challenge.rb
  config/sidekiq.yml
Labels: Review / Feedback Needed

#1360 Bugfix: Invalid Submission on challenge rules acceptance
  app/services/grader_service.rb
  db/migrate/20200419194412_remove_accepted_dataset_toc_from_challenge_participants.rb
  db/schema.rb
  spec/factories/challenge_participant_factory.rb
Labels: Review / Feedback Needed

#1370 Fix organizer_id Rollbar error
  app/policies/participant_challenge_policy.rb
Labels: Review / Feedback Needed

#1371 Fix seeds and db/schema.rb
  db/schema.rb
  db/seeds.rb
Labels: Review / Feedback Needed

#1373 Add href to links in tabular table of contents
  app/javascript/stimulus_js/controllers/challenge_overview_controller.js
Labels: Review / Feedback Needed

#1375 Fix incorrect LEFT_JOIN query for participant_challenges
  app/controllers/participants_controller.rb
  app/policies/participant_challenge_policy.rb
Labels: Review / Feedback Needed

#1374 Add categories and organizers to challenge export and import
  app/models/challenge.rb
  app/models/concerns/challenges/import_constants.rb
  app/serializers/export/category_challenge_serializer.rb
  app/serializers/export/challenge_serializer.rb
  app/serializers/export/challenges_organizer_serializer.rb
  spec/serializers/export/category_challenge_serializer_spec.rb
  spec/serializers/export/challenges_organizer_serializer_spec.rb
Labels: Review / Feedback Needed

#1358 remvoing badges from tooltip
  app/views/participants/_tooltip_profile.html.erb
Labels: Review / Feedback Needed

#1376 Fix Ui of CKeditor for admin also fix ul element
  app/admin/blog.rb
  app/admin/challenge_call.rb
  app/admin/job_posting.rb
  app/admin/participation_terms.rb
  app/assets/stylesheets/ckeditor.scss
Labels: Review / Feedback Needed

#1367 Render sponsor logos in challenge overview
  app/controllers/challenges_controller.rb
  app/models/organizer.rb
  app/views/challenges/show.html.erb
Labels: Review / Feedback Needed

#1362 Send reconfirmation e-mail after e-mail change only in production
  app/models/participant.rb
Labels: Review / Feedback Needed

#1340 Add service to get baseline discourse and show on challenge overview
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/challenges_controller.rb
  app/models/challenge.rb
  app/services/discourse/fetch_baseline_tag_service.rb
  app/views/challenges/discussions/_discussion_list.html.erb
  app/views/challenges/discussions/show.html.erb
  app/views/challenges/show.html.erb
  app/views/challenges/show/_baseline_discussions.html.erb
  app/views/challenges/show/_sidenav.html.erb
  spec/rails_helper.rb
  spec/services/discourse/fetch_baseline_tag_service_spec.rb
  spec/vcr/discourse_api/baseline_tag/success.yml
Labels: Review / Feedback Needed

#1357 removing the admin ratings
  app/views/participants/_show_reputation.erb
  app/views/participants/_show_temporary_reputation.erb
Labels: Review / Feedback Needed

#1331 Add top five contributors
  app/controllers/challenges_controller.rb
  app/models/challenge.rb
  app/views/challenges/show.html.erb
  app/views/challenges/show/_latest_five_submissions.html.erb
  app/views/challenges/show/_sidenav.html.erb
  app/views/challenges/show/_top_five_leaderboards.html.erb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/leaderboards/index.html.erb
  app/views/submissions/_submissions.html.erb
  app/views/submissions/index.html.erb
Labels: Review / Feedback Needed

#1366 Remove organizer_id from participants
  db/migrate/20200420142821_remove_organizer_id_from_participants.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/clef/clef.rb
  lib/tasks/set_organizers_for_participant.rake
  spec/features/leaderboard/leaderboard_invisible_completed_challenge_spec.rb
  spec/policies/submission_policy_spec.rb
Labels: Review / Feedback Needed

#1364 Return masthead partial
  app/controllers/api/v1/challenges/challenges_controller.rb
  config/routes.rb
  spec/requests/api/v1/challenges/challenges_controller_spec.rb
Labels: Review / Feedback Needed

#1356 Feature/improve filter url
  app/assets/javascripts/controllers/challenges_controller.js
  app/helpers/challenges_helper.rb
  app/javascript/stimulus_js/controllers/challenges_controller.js
  app/models/challenge.rb
  app/services/challenges/filter_service.rb
  app/views/challenges/index.html.erb
  app/views/shared/challenges/_filter.html.erb
  spec/services/challenges/filter_service_spec.rb
Labels: Review / Feedback Needed

#1379 changing the community icon
  app/assets/images/img/community.svg
  app/assets/stylesheets/application-redesign.css.scss
  app/views/landing_page/_discourse_top_contributors.html.erb
Labels: Review / Feedback Needed

#1359 badges and rating fixes
  app/controllers/user_rating_controller.rb
  app/jobs/badges_daily_job.rb
  app/jobs/discourse_badges_daily_job.rb
  app/jobs/rollback_badges_job.rb
  app/services/discourse/fetch_badges_service.rb
  config/application.yml.example
Labels: Review / Feedback Needed

#1381 get user profile tooltip to API call
  app/controllers/api/v1/participants_controller.rb
  app/helpers/participants_helper.rb
  app/javascript/stimulus_js/controllers/participants_controller.js
  app/views/blogs/_blog_post.html.erb
  app/views/blogs/show.html.erb
  app/views/challenges/_clef_participants.html.erb
  app/views/challenges/discussions/_discussion_list.html.erb
  app/views/challenges/teams/_member_list.html.erb
  app/views/landing_page/_blog_post.html.erb
  app/views/landing_page/_discourse_top_contributors.html.erb
  app/views/landing_page/index.html.erb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/members/_members.html.erb
  app/views/participant_challenges/_participant_challenge_rows.erb
  app/views/participants/_discourse_posts_list.html.erb
  app/views/participants/_get_user_profile.html.erb
  app/views/participants/_name_avatar.html.erb
  app/views/participants/_user_link.html.erb
  app/views/rating_leaderboard/_rating_leaderboard.html.erb
  app/views/shared/discourse/_topics_list.html.erb
  app/views/submissions/_submissions.html.erb
  config/routes.rb
  spec/requests/api/v1/participants_controller_spec.rb
Labels: Review / Feedback Needed

#1380 fix for google analytics to track hash
  app/views/layouts/_google_analytics_body.html.erb
Labels: Review / Feedback Needed

#1389 Fix status filter JS and nil, blank prize filter
  app/javascript/stimulus_js/controllers/challenges_controller.js
  app/models/challenge.rb
Labels: Review / Feedback Needed

#1383 Add Discourse::RemoveUsersFromGroupService
  app/jobs/discourse/remove_users_from_group_job.rb
  app/models/challenge_participant.rb
  app/models/challenges_organizer.rb
  app/models/participant_organizer.rb
  app/services/discourse/remove_users_from_group_service.rb
  spec/services/discourse/remove_users_from_group_service_spec.rb
  spec/support/shared_examples/discourse_service_object_spec.rb
  spec/vcr/discourse_api/remove_users_from_group/failure_username_already_out_of_group.yml
  spec/vcr/discourse_api/remove_users_from_group/failure_username_does_not_exist_in_discourse.yml
  spec/vcr/discourse_api/remove_users_from_group/success.yml
Labels: Review / Feedback Needed

#1386 Allow to export/import dataset files for challenges
  app/models/concerns/challenges/import_constants.rb
  app/serializers/export/challenge_serializer.rb
  app/services/challenges/import_service.rb
  spec/requests/api/v1/challenges/challenges_controller_spec.rb
  spec/serializers/export/dataset_file_serializer_spec.rb
Labels: Review / Feedback Needed

#1361 Submission Flow v2 (+ ACE, + EvaluationsAPI)
  Gemfile
  Gemfile.lock
  app/assets/images/img/gitlab-instruction-1.png
  app/assets/images/img/gitlab-instruction-2.png
  app/assets/images/img/gitlab-instruction-3.png
  app/assets/images/img/gitlab-instruction-4.png
  app/assets/images/img/gitlab-instruction-arrow.png
  app/assets/images/img/submission-artifact.png
  app/assets/images/img/submission-code.png
  app/assets/images/img/submission-repository.png
  app/assets/javascripts/application.js
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/challenges_controller.rb
  app/controllers/submissions_controller.rb
  app/javascript/stimulus_js/controllers/code_based_submission_controller.js
  app/jobs/submission_grader_job.rb
  app/models/challenge.rb
  app/models/concerns/challenges/import_constants.rb
  app/serializers/api/submission_file_serializer.rb
  app/services/evaluations_api_service.rb
  app/views/challenges/tabs/_details_form.html.erb
  app/views/challenges/tabs/_submissions_form.html.erb
  app/views/submissions/new.html.erb
  app/views/submissions/new/_artifact.html.erb
  app/views/submissions/new/_choose.html.erb
  app/views/submissions/new/_clef_form.html.erb
  app/views/submissions/new/_code.html.erb
  app/views/submissions/new/_form.html.erb
  app/views/submissions/new/_gitlab.html.erb
  app/views/submissions/new/_no_submissions.html.erb
  config/application.yml.example
  config/initializers/evaluations_api.rb
  db/migrate/20200410040516_add_column_evaluator_type_cd_to_challenges.rb
  db/migrate/20200419232647_add_submission_type_to_submission_file.rb
  db/schema.rb
  spec/support/config/vcr.rb
Labels: Review / Feedback Needed

#1392 Order blog posts by seq :asc and posted_at :desc
  app/controllers/blogs_controller.rb
  spec/controllers/blogs_controller_spec.rb
Labels: Review / Feedback Needed

#1396 Send newsletter_email notifications to AICrowd admins
  app/controllers/api/v1/challenges/newsletter_emails_controller.rb
  app/forms/newsletter_email_form.rb
  app/javascript/stimulus_js/controllers/newsletter_email_form_controller.js
  app/jobs/admin/newsletter_email_notification_job.rb
  app/mailers/admin/newsletter_email_notification_mailer.rb
  app/mailers/organizers/newsletter_email_mailer.rb
  app/models/participant.rb
Labels: Review / Feedback Needed

#1395 Fix submissions#index page 5xx when challenge does not have active round
  app/controllers/submissions_controller.rb
  app/helpers/tabs_helper.rb
  app/views/submissions/index.html.erb
Labels: Review / Feedback Needed
