Repository AIcrowd/AIcrowd, pull requests merged in 2020-03, with the labels that each got.

#1192 Remove unused code from app/helpers directory
  app/helpers/date_helper.rb
  app/helpers/devise_helper.rb
  app/helpers/files_helper.rb
  app/helpers/images_helper.rb
  app/helpers/landing_page_helper.rb
  app/helpers/leaderboard_videos_helper.rb
  app/helpers/meta_tags_helper.rb
  app/helpers/organizers_helper.rb
  app/helpers/participants_helper.rb
  app/helpers/s3_files_helper.rb
  app/helpers/tabs_helper.rb
  app/helpers/team_helper.rb
Labels: Review / Feedback Needed

#1145 Feature/participant has many organizer
  app/controllers/challenges_controller.rb
  app/controllers/members_controller.rb
  app/controllers/organizers_controller.rb
  app/helpers/submissions_helper.rb
  app/models/organizer.rb
  app/models/participant.rb
  app/models/participant_organizer.rb
  app/policies/challenge_policy.rb
  app/policies/dataset_file_policy.rb
  app/policies/leaderboard_policy.rb
  app/policies/member_policy.rb
  app/policies/ongoing_leaderboard_policy.rb
  app/policies/organizer_policy.rb
  app/policies/participant_challenge_policy.rb
  app/policies/participant_policy.rb
  app/policies/submission_policy.rb
  app/policies/task_dataset_file_policy.rb
  app/views/challenges/tabs/_details_form.html.erb
  app/views/organizers/_subnav.html.erb
  db/migrate/20200214084730_create_participant_organizers.rb
  db/schema.rb
  lib/tasks/set_organizers_for_participant.rake
  spec/controllers/clef_tasks_controller_spec.rb
  spec/factories/participant_factory.rb
  spec/factories/participant_organizers.rb
  spec/features/challenges/challenge_datasets_spec.rb
  spec/features/challenges/create_challenge_spec.rb
  spec/features/challenges/private_challenge_spec.rb
  spec/features/challenges_controller_spec.rb
  spec/features/clef_tasks_controller_spec.rb
  spec/policies/challenge_policy_spec.rb
  spec/policies/dataset_file_policy_spec.rb
  spec/policies/leaderboard_policy_spec.rb
  spec/policies/ongoing_leaderboard_policy_spec.rb
  spec/policies/organizer_policy_spec.rb
  spec/policies/participant_policy_spec.rb
  spec/policies/submission_policy_spec.rb
Labels: Review / Feedback Needed

#1201 Add Discourse::ApiClient class and remove discourse_api gem
  Gemfile
  Gemfile.lock
  app/services/discourse/api_client.rb
  app/services/discourse/base_service.rb
  app/services/discourse/create_category_service.rb
  app/services/discourse/update_category_service.rb
  spec/rails_helper.rb
  spec/services/discourse/create_category_service_spec.rb
  spec/services/discourse/update_category_service_spec.rb
Labels: Review / Feedback Needed

#1203 Fix Discourse username not changing when participant name changes
  app/controllers/participants_controller.rb
Labels: bug

#1199 Challenge Subnav: Reorder Tabs & Add show policies
  app/policies/challenge_policy.rb
  app/views/challenges/show/_subnav.html.erb
  app/views/leaderboards/index.html.erb
  app/views/submissions/index.html.erb
Labels: Review / Feedback Needed

#1181 Multiple organizers support for one challenge
  app/controllers/api/base_controller.rb
  app/controllers/challenges_controller.rb
  app/controllers/landing_page_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/submissions_helper.rb
  app/models/challenge.rb
  app/models/challenges_organizer.rb
  app/models/organizer.rb
  app/policies/challenge_policy.rb
  app/policies/clef_task_policy.rb
  app/policies/dataset_file_policy.rb
  app/policies/leaderboard_policy.rb
  app/policies/member_policy.rb
  app/policies/ongoing_leaderboard_policy.rb
  app/policies/organizer_policy.rb
  app/policies/participant_challenge_policy.rb
  app/policies/submission_policy.rb
  app/policies/task_dataset_file_policy.rb
  app/queries/default_scope_by_role_query.rb
  app/services/challenges/import_service.rb
  app/views/challenges/_form.html.erb
  app/views/challenges/edit.html.erb
  app/views/challenges/tabs/_details_form.html.erb
  app/views/challenges/tabs/_submissions_form.html.erb
  app/views/challenges/update.js.erb
  app/views/shared/challenges/_listing.html.erb
  app/views/shared/challenges/_masthead.html.erb
  app/views/submissions/new.html.erb
  db/migrate/20200228081303_create_challenges_organizers.rb
  db/schema.rb
  lib/tasks/challenges.rake
  spec/controllers/clef_tasks_controller_spec.rb
  spec/factories/challenge_factory.rb
  spec/factories/challenges_organizer_factory.rb
  spec/factories/participant_factory.rb
  spec/features/admins/admin_crawls_site.rb
  spec/features/challenges/challenge_datasets_spec.rb
  spec/features/challenges/create_challenge_spec.rb
  spec/features/challenges/private_challenge_spec.rb
  spec/features/challenges_controller_spec.rb
  spec/features/participants/participant_crawls_site.rb
  spec/features/public/public_user_crawls_site.rb
  spec/policies/challenge_policy_spec.rb
  spec/policies/dataset_file_policy_spec.rb
  spec/policies/leaderboard_policy_spec.rb
  spec/policies/ongoing_leaderboard_policy_spec.rb
  spec/policies/submission_policy_spec.rb
  spec/queries/default_scope_by_role_query_spec.rb
  spec/requests/api/external_graders_controller/external_graders_controller_GET_spec.rb
  spec/requests/api/external_graders_controller/external_graders_controller_INFO_spec.rb
  spec/requests/api/external_graders_controller/external_graders_controller_PATCH_spec.rb
  spec/requests/api/external_graders_controller/external_graders_controller_POST_spec.rb
  spec/requests/api/external_graders_controller/external_graders_controller_PRESIGN_spec.rb
  spec/requests/api/external_graders_controller/external_graders_post_challenge_submissions_spec.rb
  spec/requests/api/submissions_controller_spec.rb
  spec/services/challenges/import_service_spec.rb
Labels: Review / Feedback Needed

#1224 Improve test config
  config/environments/test.rb
  spec/support/config/vcr.rb
  test.rb
  tmpfile
  touchfile
Labels: Review / Feedback Needed

#1221 Fix nil exception on @current_round in leaderboards#index
  app/views/leaderboards/index.html.erb
Labels: Review / Feedback Needed, bug

#1193 Display Discourse posts on Posts tab
  app/controllers/participants_controller.rb
  app/helpers/discourse_helper.rb
  app/services/discourse/create_category_service.rb
  app/services/discourse/fetch_user_posts_service.rb
  app/services/discourse/update_category_service.rb
  app/views/participants/_discourse_posts_list.html.erb
  app/views/participants/show.html.erb
  config/application.yml.example
  spec/rails_helper.rb
  spec/services/discourse/create_category_service_spec.rb
  spec/services/discourse/fetch_user_posts_service_spec.rb
  spec/services/discourse/update_category_service_spec.rb
  spec/vcr/discourse_api/create/success.yml
  spec/vcr/discourse_api/create/success_generated_new_category_name.yml
  spec/vcr/discourse_api/create/success_truncated_category_name.yml
  spec/vcr/discourse_api/data_explorer_queries/user_posts/success.yml
  spec/vcr/discourse_api/update/success.yml
  spec/vcr/discourse_api/update/success_generated_new_category_name.yml
  spec/vcr/discourse_api/update/success_truncated_category_name.yml
Labels: Review / Feedback Needed

#1230 Display Discourse top contributors on Homepage
  app/controllers/landing_page_controller.rb
  app/services/discourse/base_service.rb
  app/services/discourse/fetch_challenge_posts_service.rb
  app/services/discourse/fetch_top_contributors_service.rb
  app/views/landing_page/_discourse_top_contributors.html.erb
  app/views/landing_page/index.html.erb
  config/application.yml.example
  spec/rails_helper.rb
  spec/services/discourse/fetch_top_contributors_service_spec.rb
  spec/vcr/discourse_api/data_explorer_queries/top_contributors/success.yml
Labels: Review / Feedback Needed

#1232 Handle missing ENV variables in Discourse services
  app/services/discourse/fetch_challenge_posts_service.rb
  app/services/discourse/fetch_top_contributors_service.rb
  app/services/discourse/fetch_user_posts_service.rb
Labels: bug

#1231 Removed organiser details from Participants ActiveAdmin
  app/admin/participant.rb
Labels: Review / Feedback Needed

#1234 Update Discussion page with correct layout
  app/controllers/challenges/discussions_controller.rb
  app/helpers/discourse_helper.rb
  app/services/discourse/fetch_challenge_posts_service.rb
  app/services/discourse/fetch_challenge_topics_service.rb
  app/views/challenges/discussions/show.html.erb
  app/views/shared/discourse/_posts_list.html.erb
  config/application.yml.example
  spec/services/discourse/fetch_challenge_topics_service_spec.rb
  spec/vcr/discourse_api/challenge_topics/success.yml
  spec/vcr/discourse_api/data_explorer_queries/challenge_posts/success.yml
Labels: Review / Feedback Needed

#1227 Insights: Add Axis Titles + Bug Fix for single round score dropdown
  app/javascript/stimulus_js/controllers/chart_controller.js
  app/views/insights/_charts/_submissions_vs_time.html.erb
  app/views/insights/_charts/_top_score_vs_time.html.erb
Labels: Review / Feedback Needed

#1240 Change class name of reference
  app/models/organizer.rb
Labels: Review / Feedback Needed

#1217 Fix View button in leaderboards listing
  app/assets/stylesheets/application-redesign.css.scss
  app/views/leaderboards/_leaderboards.html.erb
Labels: bug

#1246 Bugfix in rating displays
  app/assets/stylesheets/application-redesign.css.scss
  app/views/participants/_challenge_list.html.erb
  app/views/rating_leaderboard/index.html.erb
Labels: Review / Feedback Needed

#1247 Fix recent Rollbar errors
  app/controllers/insights_controller.rb
  app/views/insights/index.html.erb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/rating_leaderboard/_rating_leaderboard.html.erb
  app/views/rating_leaderboard/index.html.erb
  app/views/rating_leaderboard/index.js.erb
Labels: Review / Feedback Needed

#1248 Remove EmailDigestJob that's raising errors
  app/jobs/email_digest_job.rb
  app/mailers/email_digest_mailer.rb
  config/schedule.yml
  spec/jobs/email_digest_job_spec.rb
  spec/mailers/email_digest_mailer_spec.rb
Labels: Review / Feedback Needed

#1257 Bugfix/links and css fixes
  app/views/participants/_challenge_list.html.erb
  app/views/participants/_user_link.html.erb
  app/views/team_members/index.html.erb
Labels: Review / Feedback Needed

#1256 User tooltip rendering in Discourse views
  app/assets/stylesheets/application-redesign.css.scss
  app/views/challenges/discussions/show.html.erb
  app/views/landing_page/_discourse_top_contributors.html.erb
  app/views/participants/_discourse_posts_list.html.erb
  app/views/shared/discourse/_topics_list.html.erb
Labels: Review / Feedback Needed

#1259 Fix db/schema.rb file
  db/schema.rb
Labels: Review / Feedback Needed

#1258 Add unsubscribe from organizers newsletter functionality
  app/controllers/email_preferences_controller.rb
  app/views/email_preferences/_form.html.erb
  db/migrate/20200319083607_add_agreed_to_organizers_newsletter_to_participants.rb
  db/schema.rb
  spec/factories/participant_factory.rb
  spec/features/email_preferences_controller_spec.rb
Labels: Review / Feedback Needed

#1265 Gemfile: Fix dups & simplify
  Gemfile
  Gemfile.lock
Labels: Review / Feedback Needed

#1250 Fix delete member from organiser
  app/controllers/members_controller.rb
Labels: Review / Feedback Needed

#1280 Update sidekiq-unique-jobs gem because 6.0.15 version was unpublished
  Gemfile
  Gemfile.lock
Labels: bug

#1283 Bugfix: Fixed wrong logic to check for full teams
  app/models/team.rb
  app/policies/team_policy.rb
Labels: High Priority, Review / Feedback Needed, bug

#1281 Fix Review Apps Config
  app.json
  config/application.yml.example
  config/environments/staging.rb
  spec/models/team_spec.rb
Labels: Review / Feedback Needed

#1287 Fetch assets from server for review apps
  app.json
  config/environments/staging.rb
Labels: Review / Feedback Needed

#1286 Fix broken ongoing_leaderboards SQL query
  app/policies/ongoing_leaderboard_policy.rb
Labels: Review / Feedback Needed, bug

#1260 Create category tag to challenge form
  app/assets/javascripts/controllers/challenges_controller.js
  app/controllers/challenges_controller.rb
  app/helpers/challenges_helper.rb
  app/views/challenges/tabs/_details_form.html.erb
Labels: Review / Feedback Needed

#1282 Improve og meta tags for submissions
  app/helpers/application_helper.rb
  app/helpers/media_helper.rb
  app/helpers/meta_tags_helper.rb
  app/views/layouts/application.html.erb
  app/views/submissions/show.html.erb
Labels: Review / Feedback Needed
