Repository AIcrowd/AIcrowd, pull requests merged in 2020-07, with the labels that each got.

#1606 Synchronise participants with Discourse
  app/jobs/discourse/upsert_user_job.rb
  app/models/participant.rb
  app/services/discourse/upsert_user_service.rb
  lib/tasks/discourse.rake
  spec/services/discourse/upsert_user_service_spec.rb
  spec/vcr/discourse_api/update_user/partcipant_does_not_exist_success.yml
  spec/vcr/discourse_api/update_user/partcipant_exists_success.yml
Labels: Review / Feedback Needed

#1605 Fix baseline condition
  app/controllers/leaderboards_controller.rb
  db/migrate/20200630120007_change_base_leaderboard_baseline_default.rb
  db/migrate/20200630120421_update_leaderboards_to_version_24.rb
  db/migrate/20200630120601_change_disentanglement_leaderboard_baseline_default.rb
  db/migrate/20200630120822_update_ongoing_leaderboards_to_version_8.rb
  db/schema.rb
  db/views/leaderboards_v24.sql
  db/views/ongoing_leaderboards_v08.sql
  lib/tasks/update_baseline.rake
Labels: Review / Feedback Needed

#1602 Use organizer username as Discourse API username when creating topic
  app/services/discourse/api_client.rb
  app/services/discourse/base_service.rb
  app/services/discourse/create_category_service.rb
  spec/services/discourse/create_category_service_spec.rb
  spec/support/shared_examples/discourse_service_object_spec.rb
  spec/vcr/discourse_api/create/success_not_existing_username.yml
  spec/vcr/discourse_api/create/success_participant_username.yml
Labels: Review / Feedback Needed

#1592 N days of ML: friends-followers leaderboard
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/follows_controller.rb
  app/controllers/leaderboards_controller.rb
  app/controllers/participants_controller.rb
  app/helpers/follows_helper.rb
  app/helpers/participants_helper.rb
  app/models/follow.rb
  app/models/participant.rb
  app/views/follows/refresh.js.erb
  app/views/leaderboards/_filter_leaderboards.html.erb
  app/views/participants/_followers.html.erb
  app/views/participants/_following.html.erb
  app/views/participants/_masthead.html.erb
  app/views/participants/show.html.erb
  app/views/shared/challenges/_follow_button.html.erb
  app/views/shared/challenges/_masthead_extra.html.erb
  config/routes.rb
  spec/controllers/follows_controller_spec.rb
Labels: Review / Feedback Needed

#1614 Fix foreign key violation issue for participants
  app/models/participant.rb
  lib/tasks/participant_associative.rake
Labels: Review / Feedback Needed

#1615 Don't raise error on Discourse::TooManyRequests error
  app/services/discourse/base_service.rb
Labels: Review / Feedback Needed

#1541 Added Minor tooltip additions
  app/helpers/challenges_helper.rb
  app/views/shared/challenges/_dataset_file.html.erb
  app/views/shared/challenges/_listing.html.erb
  app/views/shared/challenges/_masthead_pills.html.erb
Labels: Work in progress

#1493 Freeze leaderboard Feature
  app/controllers/challenges_controller.rb
  app/controllers/leaderboards_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/leaderboard_helper.rb
  app/models/challenge_round.rb
  app/models/concerns/freeze_record.rb
  app/models/leaderboard/disentaglement_leaderboard.rb
  app/models/submission.rb
  app/services/challenge_rounds/create_leaderboards_service.rb
  app/views/challenges/fields/_challenge_round_fields.html.erb
  app/views/leaderboards/_filter_leaderboards.html.erb
  app/views/leaderboards/index.html.erb
  db/migrate/20200519134737_add_freeze_column_to_challenge_round.rb
  db/schema.rb
  spec/features/leaderboards_controller_spec.rb
Labels: Review / Feedback Needed

#1616 Update activity heatmap
  app/assets/stylesheets/participants/activity_heatmap.scss
  app/javascript/stimulus_js/controllers/activity_heatmap_controller.js
  app/services/participants/activity_heatmap_service.rb
  app/views/participants/show.html.erb
  spec/services/participants/activity_heatmap_service_spec.rb
  spec/vcr/gitlab_api/fetch_calendar_activity/failure.yml
  spec/vcr/gitlab_api/fetch_calendar_activity/success.yml
Labels: Review / Feedback Needed

#1580 Move challenge masthead setters to separate concern
  app/controllers/challenges/base_controller.rb
  app/controllers/challenges/discussions_controller.rb
  app/controllers/challenges/newsletter_emails_controller.rb
  app/controllers/concerns/challenge_masthead.rb
  app/controllers/dataset_files_controller.rb
  app/controllers/dynamic_contents_controller.rb
  app/controllers/insights_controller.rb
  app/controllers/participant_challenges_controller.rb
  app/controllers/task_dataset_files_controller.rb
  app/controllers/winners_controller.rb
  config/routes.rb
Labels: Review / Feedback Needed

#1626 Handle nil exception in Blitz challenge insights tab
  app/views/insights/index.html.erb
Labels: Review / Feedback Needed, bug

#1628 Fix recent Rollbar errors
  app/controllers/insights_controller.rb
  app/policies/challenge_policy.rb
Labels: Review / Feedback Needed, bug

#1630 Fix insights tabs nil exception
  app/views/insights/index.html.erb
Labels: Review / Feedback Needed, bug

#1629 quick fix of freeze leaderboard
  app/models/concerns/freeze_record.rb
  app/views/leaderboards/index.html.erb
Labels: Review / Feedback Needed

#1627 Linkify links in challenge Overview tab, submissions and challenge rules
  app/javascript/stimulus_js/controllers/challenge_overview_controller.js
  app/javascript/stimulus_js/controllers/challenges_edit_controller.js
  app/javascript/stimulus_js/controllers/linkify_content_controller.js
  app/views/challenge_rules/show.html.erb
  app/views/submissions/_submissions.html.erb
  app/views/submissions/show.html.erb
  package.json
  yarn.lock
Labels: Review / Feedback Needed

#1621 Add Api::V1::Organizers#create and #update endpoints
  app/controllers/api/v1/base_controller.rb
  app/controllers/api/v1/organizers_controller.rb
  app/serializers/api/v1/organizer_serializer.rb
  config/routes.rb
  spec/requests/api/v1/organizers_controller_spec.rb
  spec/serializers/api/v1/organizer_serializer_spec.rb
Labels: Review / Feedback Needed

#1632 Issue : Leaderboard not showing for login user
  app/controllers/leaderboards_controller.rb
Labels: Review / Feedback Needed

#1631 Change Round Name: label to Freeze Duration:
  app/views/challenges/fields/_challenge_round_fields.html.erb
Labels: Review / Feedback Needed

#1620 Synchronise AICrowd username with Gitlab
  app/jobs/gitlab/update_username_job.rb
  app/models/participant.rb
  app/services/gitlab/api_client.rb
  app/services/gitlab/base_service.rb
  app/services/gitlab/fetch_calendar_activity_service.rb
  app/services/gitlab/fetch_user_by_external_id_service.rb
  app/services/gitlab/update_username_service.rb
  config/application.yml.example
  config/sidekiq.yml
  db/migrate/20200708225717_add_gitlab_id_to_participants.rb
  db/schema.rb
  spec/rails_helper.rb
  spec/services/gitlab/fetch_calendar_activity_service_spec.rb
  spec/services/gitlab/fetch_user_by_external_id_service_spec.rb
  spec/services/gitlab/update_username_service_spec.rb
  spec/support/config/vcr.rb
  spec/support/shared_examples/gitlab_service_object_spec.rb
  spec/vcr/gitlab_api/fetch_user_by_external_id/success.yml
  spec/vcr/gitlab_api/fetch_user_by_external_id/user_not_found.yml
  spec/vcr/gitlab_api/update_username/success.yml
  spec/vcr/gitlab_api/update_username/user_not_found.yml
Labels: Review / Feedback Needed

#1633 Add Api::V1::Organizers::ParticipantOrganizers#create and #destroy endpoints
  app/controllers/api/v1/organizers/organizers_controller.rb
  app/controllers/api/v1/organizers/participant_organizers_controller.rb
  app/controllers/api/v1/organizers_controller.rb
  app/models/participant_organizer.rb
  app/serializers/api/v1/participant_organizer_serializer.rb
  config/routes.rb
  spec/requests/api/v1/organizers/organizers_controller_spec.rb
  spec/requests/api/v1/organizers/participant_organizers_controller_spec.rb
  spec/serializers/api/v1/participant_organizer_serializer_spec.rb
Labels: Review / Feedback Needed

#1637 Simple referral functionality for landing page
  app/controllers/participants/registrations_controller.rb
  app/javascript/stimulus_js/controllers/landing_page_controller.js
  app/javascript/stimulus_js/controllers/registration_form_controller.js
  app/models/participant.rb
  app/views/devise/registrations/new.html.erb
  app/views/landing_page/index.html.erb
  db/migrate/20200714084414_add_uuid_to_participants.rb
  db/migrate/20200714101759_add_referred_by_id_to_participants.rb
  db/schema.rb
  spec/features/participants/registrations_controller_spec.rb
Labels: Review / Feedback Needed

#1638 Add Api::V1::Organizers#show endpoint
  app/controllers/api/v1/organizers/organizers_controller.rb
  app/controllers/api/v1/organizers/participant_organizers_controller.rb
  app/serializers/api/v1/organizer_serializer.rb
  app/serializers/api/v1/participant_serializer.rb
  config/routes.rb
  spec/requests/api/v1/organizers/organizers_controller_spec.rb
  spec/requests/api/v1/organizers/participant_organizers_controller_spec.rb
  spec/serializers/api/v1/organizer_serializer_spec.rb
  spec/serializers/api/v1/participant_serializer_spec.rb
Labels: Review / Feedback Needed

#1618 Fix notification message for leaderboard
  app/services/notification_service.rb
Labels: Review / Feedback Needed

#1646 Limit Participant.name to 20 characters
  app/controllers/application_controller.rb
  app/controllers/participants_controller.rb
  app/models/participant.rb
  app/views/participants/edit.html.erb
Labels: Review / Feedback Needed

#1649 Add page title for blogs
  app/helpers/meta_tags_helper.rb
Labels: Review / Feedback Needed

#1650 Fix recent Rollbar bugs
  app/assets/javascripts/modules/direct_s3_upload.js
  app/views/leaderboards/_leaderboards.html.erb
  app/views/shared/challenges/_dataset_file.html.erb
  spec/features/task_dataset_files_controller_spec.rb
Labels: Review / Feedback Needed, bug

#1642 Add side wide search functionality for challenges and participants
  app/controllers/searches_controller.rb
  app/helpers/follows_helper.rb
  app/helpers/search_helper.rb
  app/javascript/stimulus_js/controllers/search_controller.js
  app/javascript/stimulus_js/controllers/search_form_controller.js
  app/views/layouts/_header.html.erb
  app/views/searches/show.html.erb
  config/routes.rb
  spec/features/searches_controller_spec.rb
Labels: Review / Feedback Needed

#1643 Add Discourse discussions to search results
  app/assets/stylesheets/_search.scss
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/searches_controller.rb
  app/helpers/discourse_helper.rb
  app/javascript/stimulus_js/controllers/search_controller.js
  app/services/discourse/fetch_search_results_service.rb
  app/views/challenges/discussions/show.html.erb
  app/views/challenges/discussions/show.js.erb
  app/views/challenges/show/_baseline_discussions.html.erb
  app/views/participants/_discourse_posts_list.html.erb
  app/views/searches/show.html.erb
  app/views/shared/discourse/_discussions_list.html.erb
  app/views/shared/discourse/_posts_list.html.erb
  spec/features/searches_controller_spec.rb
  spec/rails_helper.rb
  spec/services/discourse/fetch_search_results_service_spec.rb
  spec/vcr/discourse_api/search/success.yml
Labels: Review / Feedback Needed

#1655 Fix broken spec on master
  spec/services/discourse/fetch_search_results_service_spec.rb
Labels: Review / Feedback Needed, bug

#1651 Add Feedback button to website
  app/admin/feedback.rb
  app/assets/stylesheets/_feedback.scss
  app/assets/stylesheets/application-redesign.css.scss
  app/controllers/api/v1/feedbacks_controller.rb
  app/javascript/stimulus_js/controllers/feedback_form_controller.js
  app/javascript/stimulus_js/helpers/alerts_helper.js
  app/mailers/feedback_mailer.rb
  app/models/feedback.rb
  app/serializers/api/v1/feedback_serializer.rb
  app/views/feedback_mailer/feedback_email.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_feedback_modal.html.erb
  config/routes.rb
  db/migrate/20200722115821_create_feedbacks.rb
  db/schema.rb
  spec/factories/feedback_factory.rb
  spec/mailers/feedback_mailer_spec.rb
  spec/requests/api/v1/feedbacks_controller_spec.rb
  spec/serializers/api/v1/feedback_serializer_spec.rb
Labels: Review / Feedback Needed

#1648 Fix challenge statistics in challenge masthead
  app/controllers/challenges_controller.rb
  app/helpers/challenges_helper.rb
  app/models/challenge.rb
  app/models/challenge_problems.rb
  app/views/shared/challenges/_masthead_extra.html.erb
  app/views/shared/challenges/_team_stat.html.erb
  spec/factories/challenge_factory.rb
  spec/factories/challenge_problem_factory.rb
  spec/helpers/challenges_helper_spec.rb
Labels: Review / Feedback Needed, bug

#1659 Text align right scores in leaderboards table
  app/views/leaderboards/_leaderboards.html.erb
  app/views/leaderboards/index.html.erb
Labels: Review / Feedback Needed

#1656 Return empty Discourse search results collection when query parameter blank
  app/services/discourse/fetch_search_results_service.rb
Labels: Review / Feedback Needed, bug

#1661 return if notification rank is equal
  app/services/notification_service.rb
Labels: Review / Feedback Needed

#1665 Fix Chartkick geo chart
  package.json
  yarn.lock
Labels: Review / Feedback Needed, bug

#1660 Add missing flag images
  app/assets/images/flags/AN.svg
  app/assets/images/flags/GA.svg
  app/assets/images/flags/GB-ENG.svg
  app/assets/images/flags/GB-NIR.svg
  app/assets/images/flags/GB-SCT.svg
  app/assets/images/flags/GB-WIS.svg
  app/assets/images/flags/GB.svg
  app/assets/images/flags/GD.svg
  app/assets/images/flags/GE.svg
  app/assets/images/flags/GF.svg
  app/assets/images/flags/GG.svg
  app/assets/images/flags/GH.svg
  app/assets/images/flags/GI.svg
  app/assets/images/flags/GL.svg
  app/assets/images/flags/GM.svg
  app/assets/images/flags/GN.svg
  app/assets/images/flags/GP.svg
  app/assets/images/flags/GQ.svg
  app/assets/images/flags/GR.svg
  app/assets/images/flags/GS.svg
  app/assets/images/flags/GT.svg
  app/assets/images/flags/GU.svg
  app/assets/images/flags/GW.svg
  app/assets/images/flags/GY.svg
  app/assets/images/flags/SA.svg
  app/assets/images/flags/SB.svg
  app/assets/images/flags/SC.svg
  app/assets/images/flags/SD.svg
  app/assets/images/flags/SE.svg
  app/assets/images/flags/SG.svg
  app/assets/images/flags/SH.svg
  app/assets/images/flags/SI.svg
  app/assets/images/flags/SJ.svg
  app/assets/images/flags/SK.svg
  app/assets/images/flags/SL.svg
  app/assets/images/flags/SM.svg
  app/assets/images/flags/SN.svg
  app/assets/images/flags/SO.svg
  app/assets/images/flags/SR.svg
  app/assets/images/flags/SS.svg
  app/assets/images/flags/ST.svg
  app/assets/images/flags/SV.svg
  app/assets/images/flags/SX.svg
  app/assets/images/flags/SY.svg
  app/assets/images/flags/SZ.svg
  app/assets/images/flags/VA.svg
  app/assets/images/flags/VC.svg
  app/assets/images/flags/VE.svg
  app/assets/images/flags/VG.svg
  app/assets/images/flags/VI.svg
  app/assets/images/flags/VN.svg
  app/assets/images/flags/VU.svg
Labels: Review / Feedback Needed, bug

#1657 Migrate DisentaglementLeaderboard to BaseLeaderboard
  app/controllers/leaderboards_controller.rb
  app/helpers/application_helper.rb
  app/helpers/leaderboard_helper.rb
  app/jobs/calculate_leaderboard_job.rb
  app/models/base_leaderboard.rb
  app/models/disentanglement_leaderboard.rb
  app/models/leaderboard.rb
  app/models/ongoing_leaderboard.rb
  app/services/new_calculate_leaderboard_service.rb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/leaderboards/index.html.erb
  lib/tasks/challenges.rake
Labels: Review / Feedback Needed

#1654 Add submissions_type field to challenge_rounds form
  app/controllers/api/v1/challenges/challenge_rounds_controller.rb
  app/controllers/challenges_controller.rb
  app/controllers/submissions_controller.rb
  app/models/challenge_round.rb
  app/views/challenges/fields/_challenge_round_fields.html.erb
  app/views/submissions/new.html.erb
  app/views/submissions/new/_artifact.html.erb
  app/views/submissions/new/_clef_form.html.erb
  app/views/submissions/new/_code.html.erb
  db/migrate/20200723090532_add_submmission_type_to_challenge_rounds.rb
  db/schema.rb
  lib/tasks/challenges.rake
Labels: Review / Feedback Needed

#1658 Remove DisentanglementLeaderboard model and table
  app/models/disentanglement_leaderboard.rb
  db/migrate/20200724153329_remove_disentaglement_leaderboards_table.rb
  db/schema.rb
  lib/tasks/challenges.rake
Labels: Review / Feedback Needed

#1664 Fix challenge statistics
  app/helpers/challenges_helper.rb
  app/models/challenge.rb
  app/views/challenges/show/_sidenav.html.erb
  app/views/challenges/show_meta_challenge.html.erb
  app/views/practice/index.html.erb
  app/views/practice/index.js.erb
  app/views/shared/challenges/_listing_compact.html.erb
  spec/helpers/challenges_helper_spec.rb
Labels: Review / Feedback Needed, bug

#1662 Remove OldParticipant references in code and database but keep data
  app/controllers/leaderboards_controller.rb
  app/services/challenge_rounds/create_leaderboards_service.rb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/leaderboards/_winners.html.erb
  db/migrate/20200727145621_add_old_participant_id_to_base_leaderboards.rb
  db/schema.rb
  lib/tasks/leaderboards.rake
Labels: Review / Feedback Needed
