Repository AIcrowd/AIcrowd, pull requests merged in 2020-02, with the labels that each got.

#1121 Remove @import declarations for not existing files
  app/assets/stylesheets/application.css.scss
Labels: bug

#1109 Fix client_side_validations on challenge edit page rounds tab
  app/assets/javascripts/controllers/challenges_controller.js
  app/views/challenges/fields/_challenge_round_fields.html.erb
Labels: bug

#1114 Fix nil exception in participant_clef_tasks#create action
  app/controllers/participant_clef_tasks_controller.rb
  spec/requests/participant_clef_tasks_controller_spec.rb
Labels: bug

#1129 Create ChallengeStats materialised view
  db/migrate/20200210143323_create_challenge_stats_materialized_view.rb
  db/schema.rb
  db/views/challenge_stats_v01.sql
Labels: bug

#1138 Fix exceptions on submissions and leaderboard pages
  app/helpers/leaderboard_helper.rb
  app/mailers/organizer/eua_notification_mailer.rb
  app/views/challenges/index.js.erb
  app/views/clef_tasks/_task_dataset_file.html.erb
  app/views/clef_tasks/show.html.erb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/shared/challenges/_media.html.erb
  app/views/submissions/_submissions.html.erb
  spec/features/clef_tasks_controller_spec.rb
  spec/features/leaderboards_controller_spec.rb
  spec/features/submissions_controller_spec.rb
Labels: Review / Feedback Needed

#1104 Remove score_title, score_secondary_title, primary_sort_order and secondary_sort_order from challenges
  app/views/leaderboards/index.html.erb
  db/migrate/20200130112658_remove_score_title_and_score_secondary_title_from_challenges.rb
  db/migrate/20200202191204_remove_primary_sort_order_cd_and_secondary_sort_order_cd_from_challenges.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/spotify/spotify.rb
  spec/factories/challenge_factory.rb
Labels: Review / Feedback Needed

#1134 Add Challenge exporting to JSON functionality
  app/controllers/challenges_controller.rb
  app/models/challenge.rb
  app/policies/challenge_policy.rb
  app/views/challenges/tabs/_admin_form.html.erb
  config/routes.rb
  spec/requests/challenges_controller_spec.rb
Labels: Review / Feedback Needed

#1149 Fix nil exception in submission_view_description(submission) method
  app/helpers/submissions_helper.rb
Labels: bug

#1151 Release 19.02.2020
  app/helpers/submissions_helper.rb
Labels: release

#1153 Release 19.02.20 - missing fixes from master
  app/helpers/leaderboard_helper.rb
  app/mailers/organizer/eua_notification_mailer.rb
  app/views/challenges/index.js.erb
  app/views/clef_tasks/_task_dataset_file.html.erb
  app/views/clef_tasks/show.html.erb
  app/views/leaderboards/_leaderboards.html.erb
  app/views/shared/challenges/_media.html.erb
  app/views/submissions/_submissions.html.erb
  spec/features/clef_tasks_controller_spec.rb
  spec/features/leaderboards_controller_spec.rb
  spec/features/submissions_controller_spec.rb
Labels: release

#1148 Update doorkeeper views
  app/views/doorkeeper/authorizations/error.html.erb
  app/views/doorkeeper/authorizations/new.html.erb
  app/views/doorkeeper/authorizations/show.html.erb
  app/views/doorkeeper/authorized_applications/index.html.erb
Labels: Review / Feedback Needed

#1141 Challenge Subnav: Priority Nav Refactor
  app/assets/javascripts/controllers/challenges_controller.js
  app/helpers/challenges_helper.rb
  app/helpers/tabs_helper.rb
  app/views/challenge_rules/show.html.erb
  app/views/challenges/show/_create_team_modal.html.erb
  app/views/challenges/show/_subnav.html.erb
  app/views/challenges/show/_subnav_link.html.erb
Labels: Review / Feedback Needed

#1155 Add try on description
  app/views/challenges/show.html.erb
Labels: Review / Feedback Needed

#1157 Export leaderboards to CSV file
  app/assets/javascripts/controllers/challenges_controller.js
  app/controllers/challenges_controller.rb
  app/controllers/leaderboards_controller.rb
  app/queries/leaderboards/select_unique_meta_keys_query.rb
  app/services/leaderboards/csv_export_service.rb
  app/views/challenges/_form.html.erb
  app/views/challenges/edit.html.erb
  app/views/challenges/tabs/_admin_form.html.erb
  app/views/challenges/update.js.erb
  config/routes.rb
  spec/queries/leaderboards/select_unique_meta_keys_query_spec.rb
  spec/requests/leaderboards_controller_spec.rb
  spec/services/leaderboards/csv_export_service_spec.rb
Labels: Review / Feedback Needed

#1160 Fix link in submission media partial
  app/views/leaderboards/_leaderboards.html.erb
  app/views/shared/challenges/_media.html.erb
  app/views/submissions/show.html.erb
Labels: bug

#1142 Add functionality to import Challenge from json
  app/controllers/challenges_controller.rb
  app/models/challenge.rb
  app/models/challenge_rules.rb
  app/models/concerns/challenges/import_constants.rb
  app/policies/challenge_policy.rb
  app/serializers/export/challenge_partner_serializer.rb
  app/serializers/export/challenge_round_serializer.rb
  app/serializers/export/challenge_rule_serializer.rb
  app/serializers/export/challenge_serializer.rb
  app/serializers/export/dataset_file_serializer.rb
  app/serializers/export/submission_file_definition_serializer.rb
  app/services/challenges/import_service.rb
  app/services/images/base64_decode_service.rb
  app/services/images/base64_encode_service.rb
  app/uploaders/image_uploader.rb
  app/uploaders/logo_image_uploader.rb
  app/views/challenges/tabs/_admin_form.html.erb
  app/views/challenges/tabs/_details_form.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/initializers/aws.rb
  config/initializers/carrierwave.rb
  config/routes.rb
  spec/factories/submission_file_definition_factory.rb
  spec/fixtures/files/json/challenge_import.json
  spec/fixtures/files/json/challenge_import_with_errors.json
  spec/fixtures/files/json/challenge_import_with_invalid_json.json
  spec/requests/challenges_controller_spec.rb
  spec/serializers/export/challenge_partner_serializer_spec.rb
  spec/serializers/export/challenge_round_serializer_spec.rb
  spec/serializers/export/challenge_rule_serializer_spec.rb
  spec/serializers/export/challenge_serializer_spec.rb
  spec/serializers/export/dataset_file_serializer_spec.rb
  spec/serializers/export/submission_file_definition_serializer_spec.rb
  spec/services/challenges/import_service_spec.rb
  spec/services/images/base64_decode_service_spec.rb
  spec/services/images/base64_encode_service_spec.rb
  spec/vcr/images/base64_encode_service/default_image_success.yml
  spec/vcr/images/base64_encode_service/failure_missing_image.yml
  spec/vcr/images/base64_encode_service/success.yml
Labels: Review / Feedback Needed

#1169 Remove unused code with html_safe or raw methods
  app/helpers/font_awesome_helper.rb
  app/helpers/jobs_helper.rb
  app/helpers/leaderboard_helper.rb
  app/helpers/submissions_helper.rb
  app/views/dataset_files/_toc_form.html.erb
Labels: Review / Feedback Needed

#1156 Create invitaion to update form
  app/assets/javascripts/controllers/challenges_controller.js
  app/assets/stylesheets/challenges/form.scss
  app/controllers/challenges_controller.rb
  app/views/challenges/fields/_invitation_fields.html.erb
  app/views/challenges/fields/_invitations_table_fields.html.erb
  app/views/challenges/tabs/_private_challenge_form.html.erb
  app/views/members/index.html.erb
  spec/features/challenges/private_challenge_spec.rb
Labels: Review / Feedback Needed

#1159 Add submissions export to CSV functionality
  app/assets/javascripts/controllers/challenges_controller.js
  app/assets/stylesheets/challenges/form.scss
  app/controllers/leaderboards_controller.rb
  app/controllers/submissions_controller.rb
  app/queries/leaderboards/select_unique_meta_keys_query.rb
  app/queries/select_unique_meta_keys_query.rb
  app/services/leaderboards/csv_export_service.rb
  app/services/submissions/csv_export_service.rb
  app/views/challenges/_form.html.erb
  app/views/challenges/_navigation.html.erb
  app/views/challenges/tabs/_admin_form.html.erb
  app/views/challenges/tabs/_misc_form.html.erb
  app/views/challenges/tabs/_rules_form.html.erb
  config/routes.rb
  spec/queries/select_unique_meta_keys_query_spec.rb
  spec/requests/submissions_controller_spec.rb
  spec/services/leaderboards/csv_export_service_spec.rb
  spec/services/submissions/csv_export_service_spec.rb
Labels: Review / Feedback Needed

#1158 Fix/improve remove participant view
  app/controllers/challenges_controller.rb
  app/policies/challenge_policy.rb
  app/views/challenges/fields/_invitations_table_fields.html.erb
  app/views/challenges/remove_invited.js.erb
  app/views/challenges/tabs/_private_challenge_form.html.erb
  config/routes.rb
  spec/features/challenges/private_challenge_spec.rb
Labels: Review / Feedback Needed

#1170 Fix yarn webpack setup
  package.json
  yarn.lock
Labels: Review / Feedback Needed, bug

#1164 CK Editor: Small fixes, Rake Tasks
  app/assets/javascripts/controllers/challenges_controller.js
  app/assets/stylesheets/application-redesign.css.scss
  app/assets/stylesheets/challenges/form.scss
  lib/tasks/challenges.rake
Labels: Review / Feedback Needed

#1165 Priority Nav: Trigger on all challenge pages
  app/assets/javascripts/controllers/challenges_controller.js
  app/assets/stylesheets/application-redesign.css.scss
  app/javascript/stimulus_js/controllers/prioritynav_controller.js
  app/views/challenges/show/_subnav.html.erb
Labels: Review / Feedback Needed

#1171 Add datatables to challenge invitations table
  app/assets/stylesheets/application-redesign.css.scss
  app/assets/stylesheets/challenges/datatable.scss
  app/assets/stylesheets/challenges/form.scss
  app/javascript/packs/application.js
  app/javascript/stimulus_js/controllers/simple_datatables_controller.js
  app/views/challenges/fields/_invitations_table_fields.html.erb
  package.json
  yarn.lock
Labels: Review / Feedback Needed

#1175 Remove switching to next tab on challenge edit page
  app/controllers/challenges_controller.rb
  app/views/challenges/fields/_submit_buttons.html.erb
  app/views/challenges/tabs/_admin_form.html.erb
  app/views/challenges/tabs/_details_form.html.erb
  app/views/challenges/tabs/_overview_form.html.erb
  app/views/challenges/tabs/_private_challenge_form.html.erb
  app/views/challenges/tabs/_rounds_form.html.erb
  app/views/challenges/tabs/_rules_form.html.erb
  app/views/challenges/tabs/_submissions_form.html.erb
  app/views/challenges/tabs/_winner_form.html.erb
  app/views/challenges/update.js.erb
  spec/features/challenges_controller_spec.rb
Labels: Review / Feedback Needed

#1179 Display challenge_round score_titles in CSV exports
  app/services/leaderboards/csv_export_service.rb
  app/services/submissions/csv_export_service.rb
  spec/services/leaderboards/csv_export_service_spec.rb
  spec/services/submissions/csv_export_service_spec.rb
Labels: Review / Feedback Needed
